### ISSUE TITLE
Processing ECG leads

### ISSUE THREAD

**Issue by cnd** [neuropsychology/NeuroKit#10]
Hello I have 3 ECG leads (different signals) loaded to pandas DataFrame

How can I process and what can I calculate using with it using NeuroKit?

**Comment by DominiqueMakowski** [comment]
@cnd for now, using neurokit2, nothing, but soon, hopefully, a lot of things... I'll keep you updated once ECG functions start to be implemented ☺️

**Comment by cnd** [comment]
@DominiqueMakowski sorry, I meant in first version was there something possible?
