### ISSUE TITLE
ecg_delineate 

### ISSUE THREAD

**Issue by francu-pixel** [neuropsychology/NeuroKit#1032]
Goodmorning,
I'm using neurokit2 for the analysis of cardiomyocytes acquisitions and it's working very well with the ECG package. I only have one doubt: I feel like ecg_delineate actually makes up the P and T detection sometimes, since these points are identified by ecg_delineate but they are not really present in the signal.
Is it a way to make a better detection of P and T peaks and allow the code to deal with the case where they are not present?

**Comment by DominiqueMakowski** [comment]
The current algorithms are kind of looking for the "best fitting" location of these waves,but there's no fallback in case the predicted location is bad. So unfortuntaly no, the current alrogithms are not "smart" enough to know whether the waves are present or not. Maybe there are better delineations algos out there that we could add
