### ISSUE TITLE
NeuroKit error: signal_smooth(): 'size' should be between 1 and length of the signal.

### ISSUE THREAD

**Issue by francu-pixel** [neuropsychology/NeuroKit#1036]
When I try to use the ecg_peaks and the ecg_delineate functions on signals of a small duration the following error appears:
NeuroKit error: signal_smooth(): 'size' should be between 1 and length of the signal.
Is this error actually related to the size of the signal or is the error related to something else that I'm not understanding?

+ other times also this kind of error appears:
The data length is too small to be segmented.
This is clearly related to the signal's lenght, but i can't understand what's the minumum lenght of a signal to be used with these functions?

Thank you in advance.

**Comment by DominiqueMakowski** [comment]
Hi! would you have a reproducible example?
