### ISSUE TITLE
ecg_quality(method='averageQRS') is not bounded 

### ISSUE THREAD

**Issue by cgastaud** [neuropsychology/NeuroKit#1052]
**Describe the bug**
In `ecg_quality()` with method averageQRS, the result is expected to be an array between 0 and 1. However, since after rescaling the signal is interpolated with a quadratic method, this property no longer holds.
This can be easily solved by either choosing a linear interpolation method or clipping the result afterwards.

**To Reproduce**
`ecg = nk.ecg_simulate(duration=10, heart_rate=70, random_state=0)`
`print(nk.ecg_quality(ecg).min(), nk.ecg_quality(ecg).max())`

**Expected behaviour**
an array between 0 and 1

**Comment by DominiqueMakowski** [comment]
That's a good point. I think we could use the same monotonic interpolation that we use for heart rate; or indeed, linear, which probably makes even more sense. Could you consider making a PR to implement the change?
