### ISSUE TITLE
EMG threshold methods: emg_activation()

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#118]
The default threshold of `emg_activation()`  is specified as a tenth of the standard deviation of the amplitude signal. However, there should be other methods of finding the appropriate threshold, one of which by BioSPPy [find_onsets()](https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/emg.py).

Give a shout if there are other implementations of this!

**Comment by DominiqueMakowski** [comment]
added mixture method (related to #148)
