### ISSUE TITLE
How to compute QRS duration time period??

### ISSUE THREAD

**Issue by advent-embedded** [neuropsychology/NeuroKit#123]
I could able to compute the indices of P, Q R, i need the duration of QRS, to arrive this i need S index of the wave. i there a in-built routine which does this

**Comment by DominiqueMakowski** [comment]
@advent-embedded Just chiming to say that we finally have a proper alienation in neurokit2. You can follow the example at https://neurokit2.readthedocs.io/en/latest/examples/ecg_delineate.html to get what you want ☺️
