### ISSUE TITLE
Continuous measure of ECG signal quality

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#124]
It is possible to get some measure of "signal quality" for each QRS complex. NK1 did that using a machine learning model. The main trick is to get the right reference template to which the QRS complexes will be compared to.

Note that for that, @hcp4715 mentioned a new [database](https://twitter.com/ScientificData/status/1227547929981878272?s=20). We could also have a "relative" quality index, basically some sort of deviation of all QRS from the mean (either that or have some sort of Mahalanobis distance [we could format all QRS as rows and all samples as columns (i.e., as featuers) and get the distance for each observation]).

However, if we have a value of "quality for each R-peak, we could then interpolate it to get a continuous index of quality, that could be used to potentially detect noisy segments.

That being said, I wonder if they are any existing and validated methods that have been published or implemented out there.

**Comment by DominiqueMakowski** [comment]
Now that we have `ecg_quality()` we should 1) add it to `ecg_process()` and 2) add it to `ecg_plot()`:

I think we could try plotting a green area in the background, but very very light (low alpha), of the top subplot (containing the raw & cleaned ECG signal).

**Comment by DominiqueMakowski** [comment]
Hi @TiagoTostas, just saw your [PR](https://github.com/PIA-Group/BioSPPy/pull/75) with the signal quality function, great job 👏 Would you agree and be interested if we/you added it also here in NK ☺️?

**Comment by DominiqueMakowski** [comment]
@TiagoTostas looking at the implementation, it seems like it requires two R peaks detectors. But is this method appropriate in the case when one only has one detector / one set of detected R peaks?

**Comment by TiagoTostas** [comment]
This SQI takes makes use of four different quality indexes. Each one of the four indexes is classified as either optimal, suspicious or unqualified and these are then used to classify the signal according to the following function:
<img width="469" alt="Screenshot 2021-01-24 at 21 07 44" src="https://user-images.githubusercontent.com/39189659/105642151-428c8280-5e88-11eb-95d4-75d02e32b75e.png">

Using one detector makes it impossible to extract one of the features, the matching degree between the QRS, sSQI. You could adjust the decision rule and use only the other indexes three indexes (power of baseline, power of QRS and kurtosis of the signal). Any particular reason for that?

**Comment by DominiqueMakowski** [comment]
Alright I should read the paper first 😁
