### ISSUE TITLE
rsp_simulate: smooth it to look more natural

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#126]
Although respiration simulation currently uses a complex model that generates pauses in inspiration and expirations, it doesn't look very natural (the breaks between are very sharp). Hence, I wonder if we should apply a smoother on top of it to make it look more natural.

**Comment by zen-juen** [comment]
`signal_smooth()` added to reduce the sharpness of the breaks between inhalation and exhalation, now visualized as such: 
```
simulated_respiration = signal_smooth(simulated_respiration,
                                       kernel='boxzen',
                                       size=sampling_rate/2)
```

![Figure_1](https://user-images.githubusercontent.com/54053748/75002897-f929fb00-54a0-11ea-833d-ff0a44c98404.png)

**Comment by zen-juen** [comment]
@DominiqueMakowski can this be closed pls? 😄

**Comment by DominiqueMakowski** [comment]
Can lah, for next issues if you make a specific commit that closes a given issue, you can write in the description of the commit `close #126` and it will automatically close the issue (and show which commit closed it) when the PR is merged 😉
