### ISSUE TITLE
ECG: Heart Rate Variability (HRV)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#131]
## HRV

- [x] Time domain
  - [x] SDANN: Standard deviation of the **average** NN intervals for each 5 min segment
  - [x] SDNNI: (i stands for *index*) Mean of the standard deviations of all the NN intervals for each 5 min segment
- [x] Frequency domain
- [ ] Time-Frequency domain
  - [ ] [Ebrahimzadeh et al. 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3913584/pdf/pone.0081896.pdf) (see TF features below)

![image](https://user-images.githubusercontent.com/8875533/130316513-ef23dbd0-3b39-4253-b030-7bf1acc4c182.png)

  - [x] short-time fourier transform
  - [x] continuous wavelet transform
  - [ ] smoothed pseudo wigner ville distribution

- [x] Non-Linear (complexity) domain
  - [x] SD1, SD2
  - [x] Sample entropy
  - [x] Approximate Entropy
  - [x] Multiscale entropy (MSE)
  - [x] Detrended fluctuation analysis
  - [x] Correlation dimension
  - [x] [Recurrence plot analysis](https://www.kubios.com/about-hrv/)
  - [x] Area asymmetry ([Yan, 2017](https://link.springer.com/article/10.1186/s12938-017-0402-3))
- [ ] ~Norms~
- [x] **documentation**

### General

- [Thorough documentation example](https://www.kubios.com/about-hrv/)
- [de Geus, E. J., Gianaros, P. J., Brindle, R. C., Jennings, J. R., & Berntson, G. G. (2019). Should heart rate variability be “corrected” for heart rate? Biological, quantitative, and interpretive considerations. Psychophysiology, 56(2), e13287.](https://onlinelibrary.wiley.com/doi/pdf/10.1111/psyp.13287%4010.1111/%28ISSN%291469-8986.sprmeeting2019)
- [Shaffer, F., & Ginsberg, J. P. (2017). An overview of heart rate variability metrics and norms. Frontiers in public health, 5, 258.](https://www.frontiersin.org/articles/10.3389/fpubh.2017.00258/full)
- [Quintana, D. S., Alvares, G. A., & Heathers, J. A. J. (2016). Guidelines for Reporting Articles on Psychiatry and Heart rate variability (GRAPH): recommendations to advance research communication. Translational psychiatry, 6(5), e803-e803.](https://www.nature.com/articles/tp201673)
- [Slides by @michagaebler (2020) on HRV](https://osf.io/4xdmv/)

### Complexity 

- [Entropy analysis of heart rate variability and its application to recognize major depressive disorder](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6597986/)
- [Entropy Analysis of Short-Term Heartbeat Interval Time](https://www.mdpi.com/1099-4300/19/10/568)

**Comment by DominiqueMakowski** [comment]
@Tam-Pham could you take a look at these super easy formulae: https://link.springer.com/article/10.1186/s12938-017-0402-3 ^^ so we can add these additional poincaré indices as it seems highly relevant especially for short-term intervals 🙏

**Comment by DominiqueMakowski** [comment]
### Time-frequency Domain Analysis (TF)

Still from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3913584/pdf/pone.0081896.pdf; 3 methods: 

- nonparametric linear TF methods based on linear filtering
  - short-time Fourier transform
  - wavelet transform
- nonparametric quadratic TF representations
  - Wigner-Ville distribution and its filtered versions (e.g., Smoothed Pseudo Wigner-Ville distribution; SPWVD)
- parametric time-varying methods
  - autoregressive models with time-varying coefficients

We might want to include some of these as generic methods under something like `signal_timefrequency` or something.


![image](https://user-images.githubusercontent.com/8875533/85942139-13e21400-b95a-11ea-8aab-caa22bb6206b.png)

> Each HRV signal is divided into 5 segments of equal length, each segment is approximately 15 seconds in time domain. The average energy of each segment was computed. The features are:
> - MAX w: maximum amount of energy in each window.
> - MIN w: minimum amount of energy in each window.
> - DIF w: difference between maximum and minimum amount of energy between windows.
> - STD w: standard deviation between energy of time windows. The obtained signal in TF domain is also divided into three frequency segments.
> - Evlf: the total energy of signal in very low frequency band (0.003–0.04) Hz, divided by length of band (0.037).
> - Elf: the total energy of signal in low frequency band (0.04–0.15) Hz, divided by length of band (0.11).
> - Ehf: the total energy of signal in high frequency band (0.15–0.4) Hz, divided by length of band (0.25).
> - Fvlf: the average of energy signal in very low frequency band (0.04–0.003) Hz.
> - Flf: the average of energy signal in low frequency band (0.04– 0.15) Hz.
> - Fhf: the average of energy signal in high frequency band (0.15– 0.4) Hz.
> - Also, we have defined the first order derivative as a feature to show the difference between adjacent windows. This derivative is the difference between the average energy in subsequent windows. This derivative for the first window(first 15 S) was computed by the difference between this window and the last 15 seconds in the second minute. So the first order derivative feature is computed as below...

**Comment by Tam-Pham** [comment]
BUMPED. need to add SDANN and SDNN index

**Comment by DominiqueMakowski** [comment]
Closing in favour of https://github.com/neuropsychology/NeuroKit/projects/5
