### ISSUE TITLE
ecg_segment()

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#176]
Since we use it a lot, we can have an exported function to extract individual heartbeats. Todo:

- [x] docstring
- [x] Add a show arg to plot them
- [x] Use it in the individual heartbeats extraction example
- [x] Fix beat window:

```python
ecg = nk.ecg_simulate(duration=15, sampling_rate=1000, heart_rate=80)
signals, info = nk.ecg_process(ecg, sampling_rate=1000)
nk.ecg_plot(signals, sampling_rate=1000)
```
![Figure_1](https://user-images.githubusercontent.com/8875533/77843710-6d5b6b00-71d2-11ea-8feb-02dee54167ac.png)

This `*_segment()` function could be potentially extended to other signals (EDA, PPG) to isolate some segments (peaks, beats etc.)

**Comment by zen-juen** [comment]
The beat window's issue seemed to be with extracting the correct heart rate in the `ecg_segment` internal function where:
` heart_rate = np.mean(np.diff(rpeaks) / sampling_rate * 60) `
 Have changed it to:
` heart_rate = np.mean(ecg_rate(rpeaks, sampling_rate=sampling_rate))`

**Comment by DominiqueMakowski** [comment]
Yup it fixed things 👏 

The new window is perfectly for slow BPMs: 

## 50 BPM:
![Figure_3](https://user-images.githubusercontent.com/8875533/77892270-efb45f80-72a4-11ea-9ed5-74c476ff976b.png)

## 120BPM

![Figure_4](https://user-images.githubusercontent.com/8875533/77892311-02c72f80-72a5-11ea-9d71-410a73bf8cc7.png)

But for faster BPMs (> 80) we might wanna increase the window a tiny bit so that we have the offset and onsets of the extremities

**Comment by zen-juen** [comment]
Added a constant to expand the scale for if higher rates like so:
```
    if heart_rate >= 80:
        c = 0.1
        epochs_start = epochs_start - c
        epochs_end = epochs_end + c
```

Looks better 😄 
![Figure_1](https://user-images.githubusercontent.com/54053748/77893898-1f646700-72a7-11ea-93da-c7aa9c41346e.png)

**Comment by DominiqueMakowski** [comment]
OR rather than a constant, you add a portion of the square of the scaling factor ^^ so that the more the rate increases the more it expands in a non-linear fashion 🤷‍♂ 

Although if that gets too complicated don't bother too much it's fine like this 😄
