### ISSUE TITLE
Include quality in ECG plot

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#191]
We could include the ECG signal quality in the raw/cleaned signal plot, as a background green/blue area. The only thing prior to plotting it is to rescale (`nk.rescale()`) the quality to the max and min of the signals (because they define the scale of the plot).

**Comment by zen-juen** [comment]
This is defined to the max and min of the cleaned ECG signal 


![Figure_2](https://user-images.githubusercontent.com/54053748/78856676-f2a81080-7a59-11ea-89ee-325dcc3b894f.png)

**Comment by DominiqueMakowski** [comment]
how does it look as an area (similar to pandas.area.plot()) from the minimum value to the y? and behind the plot?

**Comment by zen-juen** [comment]
You mean like this?

![Figure_1](https://user-images.githubusercontent.com/54053748/78860893-ed50c300-7a65-11ea-94c0-3f76c403609f.png)

**Comment by DominiqueMakowski** [comment]
Yeah, I'd even remove the blue outline and increase the alpha to make it even more delicate 😬

**Comment by zen-juen** [comment]
![Figure_1](https://user-images.githubusercontent.com/54053748/78960849-e5eeef80-7b21-11ea-8411-64f7bef4b19c.png)

**Comment by DominiqueMakowski** [comment]
noice! need to fix the legend tho so it's not transparent. And maybe let's try with green #4CAF50 😏
