### ISSUE TITLE
Better IO (in/out): data importing and reading 

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#199]
Reading the paragraph by @sangfrois made me think that it's true that until now, NK hadn't really focused on data reading, aside from a reader for acqknowledge files.

On the other hand, data import is usually the first issue users are faced with, especially with programming tools. 

We could definitely support some readers, and potentially in our line of design have a meta `data_read()` function to which you pass the name of the file, and based on the extension is runs under the hood the appropriate reader. It could also encompass a unified framework for resampling, names cleaning, annotations detection or whatnot.

### Existing formats

<sub>feel free to complete the list</sub>

- [x] Acqknowledge
- [ ] csv, excel, txt, ...
- [ ] WFDB ([wfdb-python](https://github.com/MIT-LCP/wfdb-python))
- [ ] BIDS ([pybids](https://github.com/bids-standard/pybids), [phys2bids](https://github.com/physiopy/phys2bids))
- [ ] EDF, EFF+
- [ ] OpenSignals .txt (Bitalino)
- [ ] ...

For formats with existing packaged implementations, we could start wrapping them (and have the packages as optional dependencies) to gain some time.

**Comment by NeuroForLunch** [comment]
I was looking for what filetypes are supported as well as how to import them (data is from thermoacoustic responses). Are wav or video files of the waves supported?
