### ISSUE TITLE
Poincaré plot improvements (HRV)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#231]
I'm talking about the plot on the right:

![image](https://user-images.githubusercontent.com/8875533/83368843-ddfa5000-a3ec-11ea-84e6-eac56558a761.png)

We could improve it by:

- [x] Add 2D density (Contour plot?) 
- [x] Add marginal densities

![image](https://user-images.githubusercontent.com/8875533/83368761-95429700-a3ec-11ea-91fd-709f2f71c510.png)

I'd keep the points but would add the contour behind them. 

The main issue here is that while it is straightforward to do with [seaborn](https://python-graph-gallery.com/82-marginal-plot-with-seaborn/), we'd have to do it directly with matplotlib (because we don't want to add seaborn as a dep).

**Comment by zen-juen** [comment]
Plotted scatterpoints only outside the boundaries of sd1 and sd2. kernel densities might be misleading about the spread of the data so I included the hist bars as well.

I still feel like it can be aesthetically improved though im not sure how @DominiqueMakowski thoughts? 😄 

![Figure_2](https://user-images.githubusercontent.com/54053748/83385607-22e9ab00-a41c-11ea-8646-87ed12a71136.png)

**Comment by DominiqueMakowski** [comment]
it's nice, I it could benefit from 1) lighter lower values that the backgrounds really whiter, 2) a bit bigger points with some alpha so that we can see overlaps, 3) restore the black oval outline from the Poincaré plot, 4) remove the outline of the boxes of the marginal densities, 5) make them closer to the figure, 6) display the figure title above the top marginal box (so that the title is for the "whole" fig)

**Comment by DominiqueMakowski** [comment]
PS: this dataset is super misleading, better use ecg_simulate or else :)

**Comment by zen-juen** [comment]
With `ecg_simulate()` : 😃 

```
ecg = nk.ecg_simulate(duration=240, method="ecgsyn")
peaks, info = nk.ecg_peaks(ecg, sampling_rate=1000)
hrv = nk.hrv_nonlinear(peaks, sampling_rate=1000, show=True)
```

![Figure_1](https://user-images.githubusercontent.com/54053748/83389335-a5756900-a422-11ea-9c4b-1fc004ae7a30.png)

**Comment by DominiqueMakowski** [comment]
gorgeous

how does it with the others in `nk.hrv(show=True)`?

**Comment by DominiqueMakowski** [comment]
very minor, can we make the histogram filled with #ccdff0 and the density line #1b6aaf 😬

**Comment by zen-juen** [comment]
```
hrv_indices = nk.hrv(peaks, sampling_rate=1000, show=True)
```
will give: 
![Figure_1](https://user-images.githubusercontent.com/54053748/83397006-8204eb00-a42f-11ea-83aa-23a7f1aa8d1e.png)

**Comment by DominiqueMakowski** [comment]
👍 

How come the marginal plots still above title and far from plot? Isn't it generated from the same code?

**Comment by zen-juen** [comment]
Because the axes (and hence including the title + gridspecs) for the poincare plot have to be redefined in `nk.hrv()` when combining all the plots together

Let me see if I can assign replicate the same result, but gridspec
