### ISSUE TITLE
GitHub actions that runs a Python script (to update the README images)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#240]
Set up a GitHub action that runs the script and updates the figures.

**Comment by Tam-Pham** [comment]
47e1ce4fd64b905899a87acd38f2c40a4416a7f5 
Added Github Action to run README, add the figures and commit to master whenever there is a push to master branch

**Comment by DominiqueMakowski** [comment]
@Tam-Pham great but can you move/config the action that automatically pushes the repo to PYPI to run after it? So that it pushes the updated version?
