### ISSUE TITLE
add eog_plot()

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#279]
@zen-juen now that we have a minimal EOG pipeline we could add _plot function with like the signal and the blinks and below the blink rate.

**Comment by zen-juen** [comment]
Potentially we could also add more labels of features once we are able to delineate potental blinks into saccades, fixations etc. 😄 

![Figure_1](https://user-images.githubusercontent.com/54053748/85429093-cc056a80-b5b0-11ea-8ddd-9c4037ba89d9.png)

**Comment by DominiqueMakowski** [comment]
good job @zen-juen 🥇 yeah we'll hopefully improve that with new features in time!

**Comment by DominiqueMakowski** [comment]
We could add a "pane" on the right similarly to ecg_plot where we plot all the detected blink epochs

**Comment by zen-juen** [comment]
```
# Get data
 eog_signal = nk.data('eog_100hz')

 # Process
eog_signals, peaks = nk.eog_process(eog_signal, sampling_rate=100)

nk.eog_plot(eog_signals, peaks, sampling_rate=100)

```

![Figure_1](https://user-images.githubusercontent.com/54053748/85977618-8a8d1900-ba0f-11ea-98c8-273ad7a99a81.png)
