### ISSUE TITLE
Make Table with HRV features

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#287]
We could have in the README a table including, as rows, all the HRV features (grouped by "domain" - time domain, frequency domain etc.) and as columns the different existing packages/implementations, and a tick mark ✔️ when said feature is available.

To format RST tables, there's this website: https://www.tablesgenerator.com/text_tables

**Comment by DominiqueMakowski** [comment]
@elaineteo2000 that could be something for you ☺️ (+ @zen-juen)

**Comment by zen-juen** [comment]
@elaineteo2000 the table looks great 😄 I've moved it to the end of this example here https://neurokit2.readthedocs.io/en/dev/examples/hrv.html rather than have it in the README
