### ISSUE TITLE
ppg_simulate: lot of variability by default in the heart rate

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#293]
```python
ppg = nk.ppg_simulate(duration=35, sampling_rate=250, heart_rate=70, random_state=333)

signals, info = nk.ppg_process(ppg, sampling_rate=250)

nk.ppg_plot(signals, sampling_rate=250)
```

![Figure_1](https://user-images.githubusercontent.com/8875533/85965920-e5fbde80-b9f0-11ea-80d9-493f96606f77.png)

@JanCBrammer it seems like there is quite a lot variability by default in the simulated PPG, which sometimes makes it very different from the specified heart_rate argument (especially for shorter signals). This could be an issue for testing etc. where people expect for instance a heart rate of about 70 when specifying 70. What do you think?

**Comment by JanCBrammer** [comment]
@DominiqueMakowski, I reduced the range of heart rate fluctuation in #307.

```Python
ppg = nk.ppg_simulate(duration=35, sampling_rate=250, heart_rate=70, random_state=333)

signals, info = nk.ppg_process(ppg, sampling_rate=250)

nk.ppg_plot(signals, sampling_rate=250)
```
![Figure_1](https://user-images.githubusercontent.com/30125107/86531691-ab4be780-bec3-11ea-81d1-e8ef03ead7a0.png)
