### ISSUE TITLE
Resources: ECG processing and features

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#31]
Collection of resources to help us getting the ECG aspect right, feel free to add more:

-----

## R-peak detection & Segmentation

- See #77 

## Artifacts

- [x] [Lipponen & Tarvainen, 2019](https://www.tandfonline.com/doi/abs/10.1080/03091902.2019.1640306)
### General
- [Guidelines for Reporting Articles on Psychiatry and Heart rate variability](https://www.nature.com/articles/tp201673)
- [Slides by @michagaebler (2020) on HRV](https://osf.io/4xdmv/)

### Complexity 

- [Entropy analysis of heart rate variability and its application to recognize major depressive disorder](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6597986/)
- [Entropy Analysis of Short-Term Heartbeat Interval Time](https://www.mdpi.com/1099-4300/19/10/568)

## Other

- [ ] [ECG-RSP phase-amplitude coupling](https://github.com/jusjusjus/pyedr/blob/master/pyedr/coupling.py)

**Comment by JohnDoenut** [comment]
To get us started with ECG processing I'm happy to add an [ECG peak detection](https://github.com/JohnDoenut/biopeaks/blob/master/biopeaks/ecg.py) algorithm to the `ecg` module. I recently benchmarked the algorithm on the [Glasgow University Database (GUDB)](http://researchdata.gla.ac.uk/716/) (see [5. Changelog](https://github.com/JohnDoenut/biopeaks) for details). Then the users could already get heart rate and -period out of their ECG data and we would have a basis for building HRV analyses. If this sounds like a good idea I'll get working on a PR soonish in the new year :) 

On a related note, here's a nice [overview](https://www.biorxiv.org/content/10.1101/722397v3.full) of popular ECG peak detection algorithms and their performance on established benchmarks.

**Comment by DominiqueMakowski** [comment]
@JohnDoenut That's great 😍 Looking forward to your PR in the next decade 😁

**Comment by DominiqueMakowski** [comment]
@Tam-Pham It would be useful to get an overview of the existing pipelines for ECG cleaning (parameters of filters etc..). For instance, biosspy uses only simple filtering:

https://github.com/PIA-Group/BioSPPy/blob/e65da30f6379852ecb98f8e2e0c9b4b5175416c3/biosppy/signals/ecg.py#L69-L76

But there are [more](https://github.com/neuropsychology/NeuroKit#general) packages and surely some publications about it :wink:

**Comment by JohnDoenut** [comment]
See #65.

**Comment by DominiqueMakowski** [comment]
Closing this in favour of the more specialized issues.
