### ISSUE TITLE
Use Warning Control instead of `print("NeuroKit warning:")`

### ISSUE THREAD

**Issue by awwong1** [neuropsychology/NeuroKit#316]
**Describe the solution you'd like**
Currently, neurokit warnings are printed using the `print` builtin function.
This should instead be replaced with calls to `warnings.warn`.

**How could we do it?**

Use [warnings.warn](https://docs.python.org/3/library/warnings.html#warnings.warn), follow [PEP 230](https://www.python.org/dev/peps/pep-0230/) for guidelines.

Example, stub `main.py` file.

```python
import warnings

class NeuroKitWarning(Warning): # UserWarning, DeprecationWarning, SyntaxWarning, RuntimeWarning
    pass

if __name__ == "__main__":
    freq = 234
    sampling_rate = 345
    nyquist = 456

    warnings.warn(
        f"Skipping requested frequency" +
        f" of {freq} Hz since it cannot be resolved at the" +
        f" sampling rate of {sampling_rate} Hz. Please increase" +
        f" sampling rate to {freq * 10} Hz or choose frequencies" +
        f" smaller than or equal to {nyquist} Hz.",
        category=NeuroKitWarning)

```
```text
main.py:17: NeuroKitWarning: Skipping requested frequency of 234 Hz since it cannot be resolved at the sampling rate of 345 Hz. Please increase sampling rate to 2340 Hz or choose frequencies smaller than or equal to 456 Hz.
  category=NeuroKitWarning)
```

**Why should we do it?**

- User control over printed warnings (suppressing warnings)
- Ability to filter out warnings that should be treated as errors

----

I would be happy to make this PR if this is something that other people are also interested in.

**Comment by DominiqueMakowski** [comment]
Great idea, it's true that printing warnings does not seem to be the cleanest way 😁 

The only thing that I'd like, if possible, is to have the warning to include that it's a neurokit warning (in the message, so it stands out that it's from our code and not related to some other package or python) and also the function where the warning is located (for us to easily retrieve and debug). This information could be contained in the tracelog, but it'd be nice to have it explicitly in the warning message so it's eventually easy to report, fix or debug.

So please open a PR with like maybe one example and then we can see how it looks like, and if it works we go ahead to improve it throughout
