### ISSUE TITLE
Enabling functions to return/print a log/dict containing parameters info and details

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#319]
That's rather a long term goal since it would require quite some work, but we can start thinking about it.

We have many functions that do a lot of heavy lifting and select the optimal parameters based on some hardcoded defaults or on some internal selection algorithms. Such parameters include filtering order, type, window, entropy parameters, PSD method and so on and so forth). It would be good to store such info, as it can be useful for an easier reporting of the said-parameters.

There are different ways of approaching this. One is for instance MNE's option to have a log and functions that print (unless explicitly silenced) a lot of details. This makes a verbose pipeline with a lot of output (but one has all the details given directly). 
In general, I personally don't really like verbose functions (so I would not vote for such option to be the *default*) 🤷‍♂️ .

Another way would be to have the functions have a `log` or `details` arg. This could either be False (or None), in which case it does nothing, or True (or `"print"`), in which case it would print the details, or a dict `{}` can be passed, in which case it would store the info there and return it. This solution would allow the propagation of a "info" dict that can go from functions to functions, being updated as it goes through, without necessarily printing it at each step.

The only issue I see with that log container is that it changes the return type (as it returns one more element), I'm not sure if that's a big deal.

So a pipeline would look like this:

```python
results, log = do_something(signal, log={})  # Empty dict is passed, updated and returned as log
results2, log = do_something_else(results, log=log)  # the log dict is updated with new info
print(log) # if the user wants to display the log
```

If `log=True`, the function would essentially print the created `log` dict, and if False, wouldn't return it nor print it.

**Comment by csavur** [comment]
@DominiqueMakowski I have an alternative solution, instead of sending a parameter would be nice if set a global flag to enable/disable the log or Set the level of the log. Hence, I would suggest using python logging (https://docs.python.org/3/howto/logging.html).

With logging, we can have control over the level of the log, such as INFO, WARNING, ERROR, etc. In addition, the end-user can write the log to a file for permanent records. 

This approach will reduce the chances of mistakes. 

What do you think?
