### ISSUE TITLE
Gamboa2008 method in `eda_findpeaks` detects features inaccurately

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#324]
While implementing a new `eda_findpeaks()` method, I realized the gamboa2008 method fails to detect onsets and peaks accurately, as such:

```
eda_signal = nk.eda_simulate(duration=30, scr_number=5, drift=0.1, noise=0)
eda_cleaned = nk.eda_clean(eda_signal)
eda = nk.eda_phasic(eda_cleaned)
eda_phasic = eda["EDA_Phasic"].values

gamboa2008 = nk.eda_findpeaks(eda_phasic, method="gamboa2008")
nk.events_plot(gamboa2008['SCR_Onsets'], eda_phasic)
```
![Figure_1](https://user-images.githubusercontent.com/54053748/87057864-f8b8b380-c239-11ea-9596-7f26206c5873.png)
and outputs:

```
{'SCR_Onsets': array([  288,   657,  5993,  6322, 11889, 12218, 17985, 18316, 24431,
        24767, 25109, 28608], dtype=int64),
 'SCR_Peaks': array([  218,   503,  1023,  6154,  6685, 12051, 12581, 18149, 18679,
        24585, 24948, 25474], dtype=int64),
 'SCR_Height': array([-0.22647179, -0.20996716,  0.78532061, -0.15086503,  0.82732578,
        -0.16449928,  0.81418294, -0.1752156 ,  0.80407588, -0.17859783,
        -0.16915728,  0.81866687])}
```

Think it'll also be a good idea if we could compare across different methods the N of features detected in our tests_* to pick up on these errors 😄

**Comment by DominiqueMakowski** [comment]
If I'm not mistaken this method was taken "as is" from biosppy. So I'd say we can keep for compatibility reasons, but mention somewhere that it does not work well...
