### ISSUE TITLE
issues for analysis of various sampling rate signals

### ISSUE THREAD

**Issue by minsooyeo** [neuropsychology/NeuroKit#326]
hello ! 

firstly, i thanks a lot for wonderful your project !

during do my own project with neurokit2, i found several problems on neurokit2 for calculating bio-medical signal features and where is problem

_below is tutorial of 'neurokit2.rsp.rsp_rrv'_ : link --> https://neurokit2.readthedocs.io/en/latest/functions.html#neurokit2.rsp.rsp_rrv

```python
>>> import neurokit2 as nk
>>>
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp, info = nk.rsp_process(rsp)
>>> rrv = nk.rsp_rrv(rsp, show=True) 
```

but, if i want to the signal with 32 sampling hz

```python
>>> import neurokit2 as nk
>>> from scipy import signal
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp = signal.resample(rsp, int((len(rsp) / 1000) * 32))
>>> rsp, info = nk.rsp_process(rsp, sampling_rate=32)
>>> rrv = nk.rsp_rrv(rsp, show=True, sampling_rate=32) 
```

these results are dismatch and i could see a warning 
```
"Neurokit warning: signal_psd(): The duration of recording is too short to support a sufficiently long window for high frequency resolution. Consider using a longer recording or increasing the `min_frequency`
"
```
on debugging code, i found a bug

![neurokit](https://user-images.githubusercontent.com/23714255/87108682-d3f62780-c29d-11ea-974b-a873757591c3.JPG)

 sampling rate should be defined dynamically not constanly.

i could find a similar issue at another function: **"nk.rsp_analyze"**

![neurokit2](https://user-images.githubusercontent.com/23714255/87108970-6e566b00-c29e-11ea-99c5-fe419aed45f3.JPG)

i think these bugs must be consider later version

if similar issues is founded, i will commit  with github ~ : )

many thanks !

**Comment by DominiqueMakowski** [comment]
Hi @minsooyeo, thanks for your feedback!

Indeed, that looks like a bug in which the sampling rate is not propagated correctly throughout the functions. 

Would you like to make a pull request with the fix?

**Comment by minsooyeo** [comment]
> Hi @minsooyeo, thanks for your feedback!
> 
> Indeed, that looks like a bug in which the sampling rate is not propagated correctly throughout the functions.
> 
> Would you like to make a pull request with the fix?

yes i will deal it

**Comment by zen-juen** [comment]
We've merged your PR - thanks for your improvements and feel free to contribute further if you pick up on more issues! 😄

**Comment by minsooyeo** [comment]
> We've merged your PR - thanks for your improvements and feel free to contribute further if you pick up on more issues! 😄

thank you !
