### ISSUE TITLE
M/EEG Microstates Resources

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#332]
There is already awesome work done 😍:

- [mne_microstates](https://github.com/wmvanvliet/mne_microstates)
- [eeg_microstates](https://github.com/Frederic-vW/eeg_microstates)
- [keypy](https://github.com/keyinst/keypy)
- Guide: [Poulsen, 2018 - microstate for EEGlab](https://www.biorxiv.org/content/10.1101/289850v1.full.pdf)

### Clustering methods

- [ ] k-means
- [x] modified k-means (in [mne_microstates](https://github.com/wmvanvliet/mne_microstates) and [eeg_microstates](https://github.com/Frederic-vW/eeg_microstates/blob/bd202ee5e218c98c6515f3427bb9fc51a8bf9dce/eeg_microstates.py#L518))
- [x] Atomize and Agglomerate Hierarchical Clustering (AAHC) (in [eeg_microstates](https://github.com/Frederic-vW/eeg_microstates/blob/bd202ee5e218c98c6515f3427bb9fc51a8bf9dce/eeg_microstates.py#L401))
- [ ] Topographic Atomize and Agglomerate Hierarchical Clustering (TAAHC) (<sub>"the only difference between TAAHC and AAHC is in how they measure the quality of the clustering. Where the AAHC uses the GEV, TAAHC uses the sum of correlations as seen in (6). This means that TAAHC does not account for the strength of the maps, but only for the similarity of their topographies"</sub>, [Poulsen, 2018](https://www.biorxiv.org/content/10.1101/289850v1.full.pdf))
- [x] PCA
- [x] ICA

#### Static properties

- [x] Proportion
- [x] Duration
- [ ] Global explained variance (GEV)
- [ ] Polarity ([see here](https://github.com/wmvanvliet/mne_microstates/commit/9a82cd6e583dd62ba89a324db88aea411cc51a8d#r40646471))
- [ ] ...

#### Dynamic properties

- [ ] Transition probabilities
- [ ] Transition matrix symmetry
- [ ] ...

#### Complexity properties

- [x] Shannon entropy
- [ ] Empirical entropy rate
- [ ] ...

#### Reproducibility analysis

See [Custo, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5736178/)

- [ ] bootstrapping to assess the accuracy of our measures
- [ ] Spatiotemporal correlation

### Papers

- Very strong critique of microstates analysis: [Shaw, 2019](https://www.mitpressjournals.org/doi/abs/10.1162/neco_a_01229)
- Source localization of microstates: [Custo, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5736178/)

**Comment by zen-juen** [comment]
Though [marjin's method](https://github.com/wmvanvliet/mne_microstates/blob/master/microstates.py) and [frederic's method](https://github.com/Frederic-vW/eeg_microstates/blob/master/eeg_microstates.py) are supposedly implementing the same modified K-means clustering algorithm, the two produces quite different results:

```

**Comment by DominiqueMakowski** [comment]
even with the same parameters and input? (i.e., same GFP peak indices and same data?)

**Comment by zen-juen** [comment]
Yes even if I do use the same GFP peak indices it is still different 🤔

**Comment by DominiqueMakowski** [comment]
With the same data submitted to clustering? Coz I think by default Frederic's version standardizes the data etc. so make sure that preprocessing steps are not included

**Comment by DominiqueMakowski** [comment]
and if differences persist, we can try going line by line with the same data to identify at which line the difference occurs, and the see how

**Comment by zen-juen** [comment]
Finally I found the part in the kmeans algorithm where frederic's and marjin's method differs 😄 

The main difference is that Frederic's method incorporates the eigenvector method whilst marjin's doesn't (though if you see his code [here](https://github.com/wmvanvliet/mne_microstates/blob/master/microstates.py#L138), the eigenvector was calculated 
 initially though later commented out!) 

Specifically it is this step that is absent from marjin's method:

![Capture](https://user-images.githubusercontent.com/54053748/87910678-f73e8500-ca9c-11ea-8dee-1308b59c1d71.PNG)

**Comment by DominiqueMakowski** [comment]
I see, interesting. @wmvanvliet do you by any chance remember the reason for commenting this step out? I.e., the normalization of the eigenvector if I understand correctly?

**Comment by wmvanvliet** [comment]
Not sure. If you feel it should be in there, feel free to submit a PR :)

**Comment by DominiqueMakowski** [comment]
Haha tbh for now I don't have the slightest idea about what's wrong or what's right. I guess that's why we're trying first to set up a ground for comparison and exploration. Will keep you updated then!

@zen-juen I think you can re-add it then, as the goal here is to stay true to the original publication.

**Comment by wmvanvliet** [comment]
Also, make sure that the random values used for initialization of the maps are the same across different algorithms.

**Comment by zen-juen** [comment]
Slight difference in the way residual noise assignment in the two algorithms!

Marjin's:
```
        # Estimate residual noise
        act_sum_sq = np.sum(np.sum(states[segmentation].T * data, axis=0) ** 2)
        residual = np.abs(data_sum_sq - act_sum_sq)
        residual /= np.float(n_samples * (n_channels - 1))

        # Next iteration
        prev_residual = residual
        i += 1
```

Frederic's (n_gfp = n_samples here):
```
        # Estimate residual noise and next iteration
        residual = prev_residual
        act_sum_sq = np.sum(np.sum(states[segmentation, :] * data, axis=1) ** 2)
        prev_residual = data_sum_sq - act_sum_sq
        prev_residual /= (n_gfp * (n_channels - 1))
        n_iter += 1
```
