### ISSUE TITLE
typeerror with nk.ecg_rsp function

### ISSUE THREAD

**Issue by saakshipathania** [neuropsychology/NeuroKit#338]
The scipy.signal.butter function is producing error in this function

**Describe the bug**
INPUT
 edr = nk.ecg_rsp(ecg_rate, sampling_rate=100)

ERROR
TypeError: butter() got an unexpected keyword argument 'fs'

**Expected behaviour**
I expected the function to produce an EDR signal samples at frequency 100 hertz.

**Screenshots**
![NEUROKITERROR](https://user-images.githubusercontent.com/66521888/87997750-a5851180-cb13-11ea-963d-67c11cff9051.PNG)

**System Specifications**

OS: Windows (WindowsPE 64bit) 
- Python: 3.7.1 
- NeuroKit2: 0.0.39

**Comment by Tam-Pham** [comment]
Hi @saakshipathania 

May I check with you which version of Scipy you are running on? It seems like your version might be before Scipy 1.2.0 and as`fs` argument should be keyword argument in `scipy.signal.butter()` from Scipy 1.2.0 onwards.

**Comment by saakshipathania** [comment]
Hi @Tam-Pham 
Thank you! My version was indeed older than Scipy 1.2.0. Will upgrade right away.
