### ISSUE TITLE
Compatibility problem with nolds when computing the entropy 

### ISSUE THREAD

**Issue by dtrocellier** [neuropsychology/NeuroKit#342]
**The new version of nolds rise an error**

dist function doesn't exist anymore in nolds>0.5 thus raise an error

Traceback (most recent call last):

  File "C:\Users\dtrocell\Documents\Python Scripts\prise_en_main_hr.py", line 119, in <module>
    psd = nk.ecg_hrv(dan_r_peak, sampling_rate= 512)

  File "C:\Users\dtrocell\Anaconda3\envs\Curiosity Project\lib\site-packages\neurokit\bio\bio_ecg.py", line 640, in ecg_hrv
    hrv["Entropy_Multiscale"] = complexity_entropy_multiscale(RRis, emb_dim=2)

  File "C:\Users\dtrocell\Anaconda3\envs\Curiosity Project\lib\site-packages\neurokit\signal\complexity.py", line 411, in complexity_entropy_multiscale
    se = nolds.sampen(temp_ts, 1, tolerance, dist="euler", debug_plot=False, plot_file=None)

  File "C:\Users\dtrocell\Anaconda3\envs\Curiosity Project\lib\site-packages\nolds\measures.py", line 764, in sampen
    dsts = dist(tVecsM[i + 1:], tVecsM[i])

TypeError: 'str' object is not callable

**To Reproduce**
Example steps to reproduce the behaviour. For instance:

>>> import neurokit as nk
>>> import numpy as np
>>>
>>> signal = np.sin(np.log(np.random.sample(666)))
>>> complexity = nk.complexity(signal)

** Way to fix the issue **

Use nolds< 0.4. As an easy and temporal solution

The issue is located [here](https://github.com/neuropsychology/NeuroKit.py/blob/master/neurokit/signal/complexity.py#L145%5D). Just pass nolds.measures.rowwise_chebyshev instead.

**Comment by DominiqueMakowski** [comment]
Hi @dtrocellier, it seems you're using neurokit1, which is outdated. You can try using the complexity functions from [neurokit2](https://neurokit2.readthedocs.io/en/latest/functions.html#module-neurokit2.complexity), that don't depend on **nolds**. However, we don't have yet a wrapper function that computes all the available indices, so you'll have to specify which index you want to compute.

PS: @Tam-Pham @zen-juen the link to some of the articles on the README (for instance the complexity one) are dead so we need to update them.
