### ISSUE TITLE
Memory Error with signal_decompose

### ISSUE THREAD

**Issue by saakshipathania** [neuropsychology/NeuroKit#354]
I am trying to decompose a list of Heart Beat Interval(HBI) signals into 5 components per signal using Singular Spectrum Analysis(SSA). The list of HBI signals include 35 signals with length ranging from 16-4000000.  There is a memory error being indicated in the command - u, s, vh = gufunc(a, signature=signature, extobj=extobj).

**Describe the bug**
MemoryError                               Traceback (most recent call last)
<ipython-input-31-a038c178f896> in <module>
      2 ssa2=[]
      3 for x in hbi:
----> 4     print(len(nk.signal_decompose(x, method="ssa",n_components= 5)))

C:\ProgramData\Anaconda3\lib\site-packages\neurokit2\signal\signal_decompose.py in signal_decompose(signal, method, n_components, **kwargs)
     61         components = _signal_decompose_emd(signal, **kwargs)
     62     elif method in ["ssa"]:
---> 63         components = _signal_decompose_ssa(signal, n_components=n_components)
     64     else:
     65         raise ValueError("NeuroKit error: signal_decompose(): 'method' should be one of 'emd'")

C:\ProgramData\Anaconda3\lib\site-packages\neurokit2\signal\signal_decompose.py in _signal_decompose_ssa(signal, n_components)
    104 
    105     # Decompose the trajectory matrix
--> 106     U, Sigma, VT = np.linalg.svd(X)
    107     d = np.linalg.matrix_rank(X)
    108 

C:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in svd(a, full_matrices, compute_uv)
   1560 
   1561         signature = 'D->DdD' if isComplexType(t) else 'd->ddd'
-> 1562         u, s, vh = gufunc(a, signature=signature, extobj=extobj)
   1563         u = u.astype(result_t, copy=False)
   1564         s = s.astype(_realType(result_t), copy=False)

MemoryError: 

**To Reproduce**
for x in hbi:
    print(len(nk.signal_decompose(x, method="ssa",n_components= 5)))

**Expected behaviour**
Expected to produce  list of length 5 elements containing the 5 reconstruction components per signal

**Screenshots**
![Capture](https://user-images.githubusercontent.com/66521888/89917270-397b6200-dc16-11ea-9497-be72295827fd.PNG)

**System Specifications**
RAM- 4GB
Internal Storage- 1TB
python: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
neurokit: 0.0.39

And copy paste the output.

**Comment by DominiqueMakowski** [comment]
In #352
