### ISSUE TITLE
Pseudo-colouring of ECG to help detect abnormalities

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#359]
Alahmadi et al.  just published [a paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237854) suggested coloring ECG signals so that abnormal components are more easily detected by the naked eyes. 

Could be interested to add as a feature to `ecg_plot()`, especially since its aesthetically quite nice and "original" (and hopefully wouldn't be too heavy as the coloring goes to an empty part - under the curve).

![image](https://user-images.githubusercontent.com/8875533/91841668-563f0e80-ec85-11ea-9a1d-a8c23818181c.png)

**Comment by likith012** [comment]
When can we expect this feature to be available?

**Comment by DominiqueMakowski** [comment]
No work in the pipes as of now, and it's not on the immediate roadmap 😕 that said, it should be too hard to code (mostly a matter of time for us), feel free to give it a try we can at least assist you!

**Comment by likith012** [comment]
Sure, will look into that during my free time.

**Comment by likith012** [comment]
Also, I am dealing with a heavily imbalanced 12 led ECG dataset (PTB xl), any suggestions on how to generate synthetic data for the undersampled ECG classes. I tried SMOTE but it didn't improve my performance score and GAN's is out of option(as they produce bad results for generating 1D signals but tend to give good results for generating spectrograms).

**Comment by DominiqueMakowski** [comment]
I'm afraid that's outside of my domain 😕 good luck tho
