### ISSUE TITLE
Implementing the new method for EDA decomposition by Amin (2019)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#36]
Apparently an improvement over cvxEDA:

- http://computationalmedicinelab.ece.uh.edu/wp-content/uploads/2017/03/Tonic_Part_Removal-2.pdf
- https://ieeexplore.ieee.org/document/8917550
- [Wickramasuriya, D. S., Amin, M., & Faghih, R. T. (2019). Skin conductance as a viable alternative for closing the deep brain stimulation loop in neuropsychiatric disorders. Frontiers in neuroscience, 13, 780.](https://www.frontiersin.org/articles/10.3389/fnins.2019.00780/full)

## Resources

- https://github.com/computational-medicine-lab/Skin-Conductance-Deconvolution
- https://github.com/computational-medicine-lab/Filter-One-Binary-Two-Continuous

**Comment by hcp4715** [comment]
One more paper about skin conductance response:
https://www.sciencedirect.com/science/article/abs/pii/S0167876013003103

Unfortuantely I am occupied by other stuff recently. But I will comeback on this later.

**Comment by DominiqueMakowski** [comment]
Thank @hcp4715 Let's keep gathering and sharing useful resources :)
