### ISSUE TITLE
Do ECG analysis functions require R peaks to be pointing upwards?

### ISSUE THREAD

**Issue by Miceuz** [neuropsychology/NeuroKit#368]
We have tried to use NeuroKit to process the ECG like this with very poor results:
![image](https://user-images.githubusercontent.com/533263/95338687-ddeaef00-08bb-11eb-861a-52fdab49df11.png)

![image](https://user-images.githubusercontent.com/533263/95339390-b0527580-08bc-11eb-954d-e89d13a14ba9.png)

Our cardiologist said that ECG signal like this is to be expected as a normal ECG on Lead I, orientation of electrical axis of a heart can result in R peak inverted like that. This particular signal was recorded with electrodes placed on chest in normal position for Lead I recording.

Is there a way to trick NeuroKit to correctly delineate such signal? We have tried inverting the signal, then R-peaks are detected correctly, then we have tried to use the detected peaks to delineate the signal, but accuracy is poor.

Can you please comment on this? I am an experienced programmer and I could put some effort into this project.

I am attaching both data and notebook illustrating the issue.
[neurokit-test.zip](https://github.com/neuropsychology/NeuroKit/files/5341150/neurokit-test.zip)

**Comment by DominiqueMakowski** [comment]
Yes, neurokit expects for now the peaks to be oriented upwards. What I would suggest is simply to reverse your ECG vector (i.e., multiply it by -1)... hopefully it should work 😁

**Comment by DominiqueMakowski** [comment]
Apologies, I read too quickly. Let us see what's going on :)

**Comment by Miceuz** [comment]
Thanks for your answer @DominiqueMakowski yes, we have tried reversing the ECG - R peaks are detected correctly in this case, but delineation still looks wrong.

![image](https://user-images.githubusercontent.com/533263/95347449-92d5d980-08c5-11eb-80e3-3aaae3e44d65.png)

![image](https://user-images.githubusercontent.com/533263/95347532-aa14c700-08c5-11eb-9e4c-37ab2c2e0760.png)

**Comment by Tam-Pham** [comment]
Hi @Miceuz 

Could you try to apply the delineate function again but with a different delineate method, say `method=dwt`?

Just so that we know if this needs to be addressed for all methods. Thanks!

**Comment by Miceuz** [comment]
Hi @Tam-Pham,

Yes, sure, 
# Results with DWT
![image](https://user-images.githubusercontent.com/533263/95363756-8c049200-08d8-11eb-9f14-3942995015b8.png)
![image](https://user-images.githubusercontent.com/533263/95363810-9de63500-08d8-11eb-8de7-c8203e048b8d.png)

# With CWT:
![image](https://user-images.githubusercontent.com/533263/95364720-da666080-08d9-11eb-9526-9d6ee91c1549.png)

while this somehow crashes:
![image](https://user-images.githubusercontent.com/533263/95364817-f833c580-08d9-11eb-82b5-9c4c6db5f6e2.png)

**Comment by Tam-Pham** [comment]
It seems like DWT manages to identify the P-peaks and T-peaks a little better when the signal is original. Could you do me one last favour, to set the show_type to all for the DWT method? 
Thanks!

**Comment by Miceuz** [comment]
Sure thing

![image](https://user-images.githubusercontent.com/533263/95367134-0a633300-08dd-11eb-80a7-dcff6401b7f8.png)
![image](https://user-images.githubusercontent.com/533263/95367203-22d34d80-08dd-11eb-8e92-c79662f22b8b.png)

**Comment by Tam-Pham** [comment]
Alright. It seems like DWT is doing great here, with a few exception. This window is probably a bit too long for your QRS complex and that's why the messiness at the end (it includes the information of the adjacent complex).

We will investigate and try to improve the peak method. But for now, is the return of DWT sufficient for you?

**Comment by Miceuz** [comment]
We are just evaluating NeuroKit right now, so this is totally fine. Thank you very much!

**Comment by JanCBrammer** [comment]
> while this somehow crashes

@Miceuz, note that this has been fixed on `dev` (#347, version 0.0.41) already.

**Comment by JanCBrammer** [comment]
Looks like in this case, only the R-peaks are inverted, not the P and T waves. This could lead to a scenario where after inversion, the R peaks are detected fine, but the delineation struggles to correctly detect P or T waves. @Tam-Pham, in how far does the delineation rely on non-inverted P and T waves?

**Comment by DominiqueMakowski** [comment]
Indeed indeed, good catch @JanCBrammer! that's the cause of this issue I think. I wonder if we could selectively revert the R-peaks or - do the R peak detection on the reverted signal :and the delineation on the raw signal 🤔

**Comment by JanCBrammer** [comment]
Although I believe that @Miceuz already worked around that by doing:

```
rpeaks = find_peaks(inverted_ecg)
waves = delineate(original_ecg, rpeaks)
```

**Comment by DominiqueMakowski** [comment]
right - I need to change my glasses 🤓

**Comment by Miceuz** [comment]
@JanCBrammer thanks, I will check it out.

**Comment by Tam-Pham** [comment]
@JanCBrammer It actually matters. If you look at @Miceuz 's plot for original and inverted signals:

> ![image](https://user-images.githubusercontent.com/533263/95367134-0a633300-08dd-11eb-80a7-dcff6401b7f8.png)
> ![image](https://user-images.githubusercontent.com/533263/95367203-22d34d80-08dd-11eb-8e92-c79662f22b8b.png)

The delineation works alright with the original signal where P and T waves are NOT inverted. I guess for this particular case, users have to inverse the signal to identify R-peaks and use the original signal for the delineation. 

P/S: we should indeed merge the dev branch soon 😅 
P/SS: @DominiqueMakowski yah u need new glasses or slow down your reading 😄

**Comment by JanCBrammer** [comment]
Thanks @Tam-Pham. So it looks like ideally we would find a way to detect inverted R-peaks and selectively re-invert them 😬

**Comment by JanCBrammer** [comment]
@Miceuz, which method did you use for R-peak detection?

neurokit (default), pamtompkins1985, hamilton2002, christov2004, gamboa2008, elgendi2010, engzeemod2012, kalidas2017, martinez2003, rodrigues2020 or promac?

**Comment by Miceuz** [comment]
@JanCBrammer  it was neurokit

I am attaching my python notebook and source data with updated DWT/CWT experiments

[neurokit-test.zip](https://github.com/neuropsychology/NeuroKit/files/5345765/neurokit-test.zip)
