### ISSUE TITLE
UnboundLocalError in eda_analyze and rsp_analyze

### ISSUE THREAD

**Issue by accer-iou** [neuropsychology/NeuroKit#370]
When I use fuction eda_analyze, I find it does not work and the Error is UnboundLocalError: local variable 'features' referenced before assignment. Please try to fix it.

**Comment by JanCBrammer** [comment]
@zhaoyanxi , please post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that exactly reproduces the issue. Also, please include the full traceback (i.e., error message) in your example. Then it will be easier for us to help you. If possible also upload the signal that produced the error.

**Comment by bananakiu** [comment]
Reporting that this is the same case for rsp_analyze.

Same issue:  UnboundLocalError: local variable 'features' referenced before assignment.

**Comment by JanCBrammer** [comment]
@bananakiu, can you post your script that causes the issue?
