### ISSUE TITLE
Analyzing 12 lead ECG

### ISSUE THREAD

**Issue by dhananjayabl** [neuropsychology/NeuroKit#377]
Can I use Neurokit2 to analyze 12 lead ECG signals?

**Comment by DominiqueMakowski** [comment]
@dhananjayabl well you can use it to clean & filter the signal, but things related to heart rate, as they depend on R-peaks detection (currently only implemented for leads where R peaks are large and upwards), will only work with the appropriate leads. We don't currently have any "multi-lead" method that would take into account all the leads (but if you find something like that, do let us know so we can see if we could implement it)
