### ISSUE TITLE
Incorrect requirement for scikit-learn

### ISSUE THREAD

**Issue by ToucheSir** [neuropsychology/NeuroKit#388]
Both [setup.py](https://github.com/neuropsychology/NeuroKit/blob/master/setup.py#L25) and [Pipfile](https://github.com/neuropsychology/NeuroKit/blob/master/Pipfile#L22) specify the wrong package name for scikit-learn. The "sklearn" [package](https://pypi.org/project/sklearn/) on PyPI hasn't been updated since 2015, and even points to the correct "scikit-learn" [package](https://pypi.org/project/scikit-learn/). This may wreak havoc with other code that uses scikit-learn, or at the very least confuse package manager dependency resolvers.

**Comment by DominiqueMakowski** [comment]
thanks for catching that! We'll probably fix it for the next version ☺️
