### ISSUE TITLE
ecg_clean does not handle method "pamtompkins1985"

### ISSUE THREAD

**Issue by avernan** [neuropsychology/NeuroKit#391]
According to docs one of the possible methods for ecg_clean is "pamtompkins1985", however none of the conditions starting from
https://github.com/neuropsychology/NeuroKit/blob/9ec5674b963cdc96709105a01a8af5c2c18c1ee5/neurokit2/ecg/ecg_clean.py#L64

checks against this particular method. This leads to a confusing error as seen in the screenshot
![image](https://user-images.githubusercontent.com/9851882/100515526-b6562b80-3174-11eb-971d-0e190b515396.png)

**Comment by Tam-Pham** [comment]
Hi @avernan 

Thank you for raising the issue! This is caused by a typo from our end. It should be "pantompkins1985" and not "pamtompkins1985".

We will correct this in our next release :)
