### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by yywangvr** [neuropsychology/NeuroKit#395]
Hello, I get the following warning:

lib/python3.7/site-packages/neurokit2/eda/eda_findpeaks.py:289: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  scrs = np.array(scrs)

Maybe a slight correction is required.  Thank you.

**Comment by DominiqueMakowski** [comment]
@Tam-Pham is there any update on this?

**Comment by JanCBrammer** [comment]
duplicate of #421.
