### ISSUE TITLE
Indices of complexity, entropy and fractal dimension

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#40]
This is a summary of the progress of implementing a comprehensive framework for complexity analysis. The goal is too carefully reimplement all indices so that it's efficient, validated and tested. 

### Entropy

- [x] Shannon entropy (neurokit2 == [pyEntrp](https://github.com/nikdon/pyEntropy))
- [x] Approximate entropy (neurokit2 == [EntroPy](https://github.com/raphaelvallat/entropy) != [pyeeg](https://github.com/forrestbao/pyeeg/blob/master/pyeeg/entropy.py#L5)  ?= [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L308))
- [x] corrected ApEn (cApEn) ([paper](https://www.mdpi.com/1099-4300/19/10/568/htm))
- [x] Sample entropy (neurokit2 == [EntroPy](https://github.com/raphaelvallat/entropy) == [nolds](https://github.com/CSchoel/nolds) [==](https://github.com/ixjlyons/entro-py/pull/2) [entro-py](https://github.com/ixjlyons/entro-py) [==](https://github.com/nikdon/pyEntropy/pull/15) [pyEntrp](https://github.com/nikdon/pyEntropy) [==](https://github.com/forrestbao/pyeeg/pull/29) [pyeeg](https://github.com/forrestbao/pyeeg/blob/master/pyeeg/entropy.py#L276) ?= [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L335))
- [x] Fuzzy entropy (neurokit2 == [entro-py](https://github.com/ixjlyons/entro-py) ?= [matlab](https://www.mathworks.com/matlabcentral/fileexchange/31888-fuzzy-entropy-and-mutual-information))
- [x] multiscale entropy (MSE) ([pyEntrp](https://github.com/nikdon/pyEntropy))
- [x] Fuzzy MSE
- [x] Composite multiscale entropy (CMSE) ([pyEntrp](https://github.com/nikdon/pyEntropy))
- [x] Fuzzy CMSE
- [x] Refined composite multiscale entropy (RCMSE) ([paper](https://www.mdpi.com/1099-4300/22/3/317/htm))
- [x] Fuzzy RCMSE
- [ ] Multidimensional Approximate Entropy (MApEn) ([paper](https://www.hindawi.com/journals/complexity/2018/4953273/))
- [ ] Generalized multiscale entropy (GMSE) ([in C](https://www.physionet.org/content/gmse/1.0.0/))
- [ ] Permutation entropy ([pyEntrp](https://github.com/nikdon/pyEntropy), [EntroPy](https://github.com/raphaelvallat/entropy))
- [ ] Multiscale permutation entropy ([pyEntrp](https://github.com/nikdon/pyEntropy))
- [ ] conditional entropy (CE) ([paper](https://www.mdpi.com/1099-4300/19/10/568/htm))
- [ ] distribution entropy (DistEn) ([paper](https://www.mdpi.com/1099-4300/19/10/568/htm))
- [ ] Spectral entropy ([EntroPy](https://github.com/raphaelvallat/entropy), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L423))
- [ ] Singular value decomposition entropy ([EntroPy](https://github.com/raphaelvallat/entropy), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L252))
- [ ] Inherent fuzzy entropy ([matlab](https://github.com/czh513/EEG-Inherent-Fuzzy-Entropy))
- [ ] Rényi entropy ([dit](https://github.com/dit/dit))
- [ ] Tsallis Entropy ([dit](https://github.com/dit/dit))
- [ ] Entropy estimation via compression coding ([PNG-Entropy](https://github.com/Sylvain-Deposit/PNG-Entropy) by [Zbili, 2020](https://www.biorxiv.org/content/10.1101/2020.08.04.236174v1))
- [ ] ...

### Fractal Dimension

- [x] detrended fluctuation analysis (DFA) (neurokit2 == [nolds](https://github.com/CSchoel/nolds), [EntroPy](https://github.com/raphaelvallat/entropy), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L550), [fathon](https://github.com/stfbnc/fathon), [dfa](https://https://github.com/dokato/dfa/blob/master/dfa.py))
- [x] multifractal detrended fluctuation analysis (MFDFA) ([fathon](https://github.com/stfbnc/fathon), [MFDA](https://github.com/LRydin/MFDFA/tree/master/MFDFA), [PyActigraphy](https://ghammad.github.io/pyActigraphy/pyActigraphy-MFDFA.html#Multifractal-DFA))
- [x] correlation dimension ([nolds](https://github.com/CSchoel/nolds), [Corr_Dim](https://github.com/jcvasquezc/Corr_Dim), [paper](https://www.hindawi.com/journals/cmmm/2014/129248/))
- [ ] Lyapunov exponent ([nolds](https://github.com/CSchoel/nolds))
- [ ] Hurst exponent ([nolds](https://github.com/CSchoel/nolds), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L582))
- [ ] Generalized Hurst exponent ([GenHust](https://github.com/PTRRupprecht/GenHurst))
- [ ] Petrosian fractal dimension ([EntroPy](https://github.com/raphaelvallat/entropy), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L125))
- [ ] Katz fractal dimension ([EntroPy](https://github.com/raphaelvallat/entropy))
- [ ] Higuchi fractal dimension ([EntroPy](https://github.com/raphaelvallat/entropy), [pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L471))
- [ ] Multiscale multifractal analysis ([matlab](https://www.physionet.org/content/mma/1.0.0/))
- [ ] ...

### Other

- [ ] Hjorth's parameters and complexity ([pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L179))
- [ ] Lempel-Ziv complexity ([EntroPy](https://github.com/raphaelvallat/entropy))
- [ ] Ficher information ([pyrem](https://github.com/gilestrolab/pyrem/blob/master/src/pyrem/univariate.py#L286))
- [ ] delay vector variance (DVV) ([paper](https://ieeexplore.ieee.org/abstract/document/1288393))
- [ ] Noise reduction ([nolitsa](https://github.com/manu-mannattil/nolitsa/blob/master/nolitsa/noise.py#L51))
- [ ] Kramers-Moyal Coefficients ([KramersMoyal](https://github.com/LRydin/KramersMoyal) by @LRydin; see [Prusseit, 2007](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.98.138103) for EEG application)

### Helpers

- [x] [Optimal Embedding Dimension](https://www.biopac.com/wp-content/uploads/Specialized_Analysis_Acq39.pdf)
- [x] [Optimal Time Delay](https://www.biopac.com/wp-content/uploads/Specialized_Analysis_Acq39.pdf): [here](http://node99.org/tutorials/ar/)
- [x] [Chaotic Attractor](https://www.biopac.com/wp-content/uploads/Specialized_Analysis_Acq39.pdf): [here](http://node99.org/tutorials/ar/)
- [ ] Chaos Decision Tree Algorithm ([matlab](https://figshare.com/s/80891dfb34c6ee9c8b34); [Toker et al., 2020](https://www.nature.com/articles/s42003-019-0715-9))

## References

- [Amarantidis, L. C., & Abásolo, D. (2019). Interpretation of entropy algorithms in the context of biomedical signal analysis and their application to EEG analysis in epilepsy. Entropy, 21(9), 840.](https://www.mdpi.com/1099-4300/21/9/840/pdf)
- [Gao, Z., Cui, X., Wan, W., & Gu, Z. (2019). Recognition of Emotional States using Multiscale Information Analysis of High Frequency EEG Oscillations. Entropy, 21(6), 609.](https://www.mdpi.com/1099-4300/21/6/609/htm)

**Comment by LRydin** [comment]
Small comment, I guess there is little point in separating _detrended fluctuation analysis_ (DFA)  and _multifractal detrended fluctuation analysis_ (MFDFA), as the latter should always be able to do DFA if you set the power/exponent `=2` :).

**Comment by DominiqueMakowski** [comment]
Thanks for that very good point 😁 I'll leave it as is just to separate the implementations (as most of DFA implementations do not allow for MDFA ;)
