### ISSUE TITLE
Butterworth filter not working

### ISSUE THREAD

**Issue by MeenaSiddharthan** [neuropsychology/NeuroKit#416]
Hi!! So I can't run nk.ecg_process to get cleaned ECG signals. 
So this is my line:
```Python
ecg_signals, ecg_info = nk.ecg_process(data["ECGBIT"], sampling_rate=sampling_rate)
```

And this is the error I got:
```
Traceback (most recent call last):
.
.
.
  File "C:\Users\m.siddharthan\AppData\Local\Continuum\anaconda3\lib\site-packages\neurokit2\signal\signal_filter.py", line 211, in _signal_filter_butterworth
    sos = scipy.signal.butter(order, freqs, btype=filter_type, output="sos", fs=sampling_rate)

TypeError: butter() got an unexpected keyword argument 'fs'
```

Is there somewhitng I'm missing? But it seemed to work to get events/get plots etc

**Comment by Tam-Pham** [comment]
Could you check what's your scipy version? Because fs is a new argument that is just added in version 1.2.0

**Comment by DominiqueMakowski** [comment]
@MeenaSiddharthan you can get the versions by running `nk.version()`

![image](https://user-images.githubusercontent.com/8875533/109098062-8e6a6a00-775b-11eb-86fb-c65691814f3f.png)

**Comment by MeenaSiddharthan** [comment]
Heyyy! Thanks! So here are my versions:
- OS: Windows (WindowsPE 64bit) 
- Python: 3.7.1 
- NeuroKit2: 0.1.1 
- NumPy: 1.15.4 
- Pandas: 0.23.4 
- SciPy: 1.1.0 
- sklearn: 0.20.1 
- matplotlib: 3.0.2

**Comment by JanCBrammer** [comment]
@MeenaSiddharthan, please upgrade your SciPy to version 1.2.0. The `fs` argument to `scipy.signal.butter` did not exist prior to the 1.2.0 version (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html).

**Comment by Tam-Pham** [comment]
Ah! Seems like your scipy is not up to date. Ya can update it to the latest and try again :)

**Comment by MeenaSiddharthan** [comment]
Yup! I upgraded scipy now everything works! Thanksss
