### ISSUE TITLE
Get time of bpm?

### ISSUE THREAD

**Issue by Mark462246** [neuropsychology/NeuroKit#417]
Hi!
I'm a university student. In my dissertation, an ECG displaying and processing program must be created. I found the NeuroKit2 yesterday and thought it could help with my work. 
Currently I want to get the bpm values from ecg record and I can see that I can get this with the ecg_process() method from ECG_Rate, but I can not find that  these bpm values (which is in ECG_Rate)  where can i find their time. The time at which time I get these bpm values.
If anyone could help with this, I would be very grateful.

**Comment by DominiqueMakowski** [comment]
>  but I can not find that these bpm values (which is in ECG_Rate) where can i find their time

I'm not sure what you mean 🤔 The "unit" of the ECG rate is in samples, meaning that each data point corresponds to one sample, which means something different depending on the sampling rate of your signal. To convert to seconds, you can divide by the sampling rate, an event occuring at the index 2000, for a signal with a sampling rate of 1000Hz, occurred at 2 seconds (2000 / 1000 = 2).
