### ISSUE TITLE
Fixing random seeds during data simulation

### ISSUE THREAD

**Issue by JohnDoenut** [neuropsychology/NeuroKit#43]
None of the `xxx_simulate()` functions take a parameter that allows for fixing the random seed.
Fixing the seed would be important for reproducible tests.

**Comment by JohnDoenut** [comment]
See #44.

**Comment by DominiqueMakowski** [comment]
👍 👍   (and thanks for the housekeeping, I have real issues respecting the 79 characters length 😁)

**Comment by JohnDoenut** [comment]
@DominiqueMakowski 

> I have real issues respecting the 79 characters length

Me as well actually, maybe at some point we could outsource the housekeeping using [Black](https://pypi.org/project/black/), I hear it's amazing!
