### ISSUE TITLE
Absence of PPG related methods in Interval Related Analysis

### ISSUE THREAD

**Issue by LaxmanSinghTomar** [neuropsychology/NeuroKit#438]
I was looking to perform Interval Related Analysis on raw PPG signals which are of resting state only in order to generate features for it so that further Machine Learning models could be used. But the documentation [page](https://neurokit2.readthedocs.io/en/latest/examples/intervalrelated.html) only mentions methods for ECG and RSP signals. So, does Neurokit support PPG based feature extraction? Or there is any other relevant section of Neurokit's documentation which could help me do what I asked above? 

Any help or pointers would be highly appreciated.

**Comment by zen-juen** [comment]
Hi @LaxmanSinghTomar! I've just added `ppg_intervalrelated` which outputs similar features as `ecg_intervalrelated` (rate max and hrv indices), example code here:

```
import neurokit2 as nk

data = nk.data("bio_resting_5min_100hz")
df, info = nk.ppg_process(data["PPG"], sampling_rate=100)
nk.ppg_intervalrelated(df, sampling_rate=100) 
```

Could you install the dev version (`pip install https://github.com/neuropsychology/neurokit/zipball/dev`) and see if these features are the ones you want?

**Comment by LaxmanSinghTomar** [comment]
Hey, @zen-juen! Thanks for the quick response. This worked and helped me get the interval related features (perhaps the same ones from HRV) which I wanted to obtain from a very long time. I wanted to know are there any other ways of feature extraction possible in Neurokit for PPG signal? Also, won't it be better to have everything related to PPG (or any other signal) at a single place in documentation?

**Comment by zen-juen** [comment]
That's great! You can find the documentation of all ppg functions here: https://neurokit2.readthedocs.io/en/dev/functions.html#module-neurokit2.ppg. Note that `ppg_eventrelated`, `ppg_intervalrelated`, and `ppg_analyze` are new functions that I just added yesterday and so you can only find them in the */dev/* branch of the readthedocs and not */latest/* since we have not merged dev into master yet!
