### ISSUE TITLE
RSA plot

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#443]
All the hrv_* functions have a `show` argument that can be set to `True` to make nice plots. All but `hrv_rsa()`. We should add a plot, though I'm not sure what's the best choice. Maybe something based on cardiac coherence visualizations, or an overlay of RSP and HR? Brainstorming is welcome

Some images from google:

![image](https://user-images.githubusercontent.com/8875533/114297387-e9c1a300-9ae2-11eb-9d90-5572e7d1edcb.png)

![image](https://user-images.githubusercontent.com/8875533/114297427-29888a80-9ae3-11eb-80b5-d36fa5e47346.png)

**Comment by zen-juen** [comment]
Possible overlay of rsp and ecg signals, extracted from [here](https://www.researchgate.net/publication/333203340_Recent_development_of_respiratory_rate_measurement_technologies)

![image](https://user-images.githubusercontent.com/54053748/114506249-19e47f80-9c64-11eb-8fb3-cd282d081908.png)

**Comment by DominiqueMakowski** [comment]
@zen-juen @Tam-Pham a plot for RSA would be nice and easy to add to essentially finalize the HRV features set

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/129818050-a3b9a31e-bd4c-4942-9d54-8d248629ae8c.png)

I'd say that a plot like that, with a) overlay of (normalized, probably a running-window normalization of like 10 seconds so that it's on the same scale throughout to help highlight the synchronization) HR & RSP rate and b) values of RSA (only when continuous RSA available) is the most efficient way of conveying the idea
