### ISSUE TITLE
How can I change the minimum requirement for calculating Frequency Domain HRV such as LF, LF/HF?

### ISSUE THREAD

**Issue by cscmaus** [neuropsychology/NeuroKit#453]
Hey guys, I love this repo! I've been using this for a while (hopefully pubs soon), for >2 min signals. But I would like to test something using 30-second signals, so while the time domain is fine, the frequency domain shows up as NAN. Is there a way to modify the minimum number of peaks/samples/time?

**Comment by Tam-Pham** [comment]
hey @csavur 

Glad you love the package and hope those pubs coming soon 😉 

For the frequency domain, the min. length of signal is defined in `signal_power()` below

https://github.com/neuropsychology/NeuroKit/blob/d96f5354b60ee222561ef85f1a7b1774cb12e431/neurokit2/signal/signal_power.py#L89

as we want to make sure that signal length is sufficient to capture at least 2 cycles of min_frequency. I would say having anything less than that would not give you reliable frequency indices. However, if you would like to have it work for much shorter signal length, what you can do is customising your own processing pipeline (following the example [here](https://neurokit2.readthedocs.io/en/latest/examples/custom.html)).

Specifically, you will need to create your own `signal_power()` function where the following loop is removed:
https://github.com/neuropsychology/NeuroKit/blob/d96f5354b60ee222561ef85f1a7b1774cb12e431/neurokit2/signal/signal_power.py#L83

Then you will need to create your own `hrv_frequency()` function where you replace the default `signal_power()` function of NeuroKit with your own:
https://github.com/neuropsychology/NeuroKit/blob/d96f5354b60ee222561ef85f1a7b1774cb12e431/neurokit2/hrv/hrv_frequency.py#L127

Note that you might see some warning that says "The duration of recording is too short to support a sufficiently long window for high frequency resolution. Consider using a longer recording or increasing the `min_frequency`". But that's expected if you decide to mofidy the above functions. 

let us know if you run into any trouble 😄
