### ISSUE TITLE
Warp electrophysiological data from clock time to brain time (Brain Time Toolbox)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#464]
The pioneering and innovative work of van Bree et al. introduces the fascinating idea of brain time, i.e., based on the oscillatory rate of electrophysiological activity, and an applied method of obtaining it.

The code is in matlab... A Python adaptation would really increase the accessibility of this new approach ☺️  

- Paper: [Clock time: a foreign measure to brain dynamics (van Bree et al.)](https://www.biorxiv.org/content/10.1101/2021.06.09.447763v1.full.pdf)
- Brain Time Toolbox *(matlab)*: https://github.com/sandervanbree/braintime

@sandervanbree do you have any existing plans for Python adaptations? If not, would you be eventually interested in such a development?

**Comment by sandervanbree** [comment]
Hi Dominique, thank you kindly for sharing our work and for pinging me here! Yes, we are considering Python development. The scope of such a project would depend on the demand and enthusiasm of the community (which is looking promising). It could be a basic implementation, or something full-fledged. The how's and when's are very much uncertain though.
