### ISSUE TITLE
Missing peaks from ecg_delineate

### ISSUE THREAD

**Issue by NurgulKaryagis** [neuropsychology/NeuroKit#473]
Hi,

I need to find all peaks in ecg data. The ecg_delineate function finds all peaks at example page. However, Q and S peaks are not found by this function and it gives KeyError when I try to plot. Why does not it give all peaks? The codes are following:

```python
path = "some/path"
raw_ecg = wfdb.rdsamp(path, channels=[0])

ecg_signal = nk.ecg_clean(raw_ecg[0], sampling_rate=360, )

_, rpeaks = nk.ecg_peaks(ecg_signal, sampling_rate=360)

plot = nk.events_plot(rpeaks["ECG_R_Peaks"][:8], ecg_signal[:2000])

_, waves_peak = nk.ecg_delineate(ecg_signal, rpeaks, sampling_rate=360)

plot = nk.events_plot([waves_peak['ECG_T_Peaks'][:3],
                       waves_peak['ECG_P_Peaks'][:3],
                       waves_peak['ECG_Q_Peaks'][:3],
                       waves_peak['ECG_S_Peaks'][:3]],ecg_signal[:12500])
```

And this is the error:

```python
Traceback (most recent call last):

  File "C:\Users\nurgul\Scripts\neurokit2.py", line 31, in <module>
    waves_peak['ECG_Q_Peaks'][:3],

KeyError: 'ECG_Q_Peaks'

```

**Comment by zen-juen** [comment]
Hi @NurgulKaryagis, the default method in `ecg_delineate` is `dwt` (discrete wavelet transform) which does not output Q-peaks indices. You'll have to pass `method="peaks"` in `ecg_delineate` to get the Q peaks. You can refer to our docstrings [here](https://neurokit2.readthedocs.io/en/dev/_modules/neurokit2/ecg/ecg_delineate.html#ecg_delineate) to see the different dictionary outputs based on the type of method passed
