### ISSUE TITLE
Could you please tell me where to find the principle of neurokit" in ecg_peaks_method.

### ISSUE THREAD

**Issue by skywalkerzhang** [neuropsychology/NeuroKit#476]
**Question and context**
I'm working on my graduation project, and I want to introduce the principle of peak detection of your project in the method section, but I haven't found it in the documents and cited papers you provided (which will be quoted in the graduation project). May I ask this principle? Can it be made public?

**Comment by DominiqueMakowski** [comment]
You mean the default peak detection method for... ECG?

**Comment by skywalkerzhang** [comment]
> You mean the default peak detection method for... ECG?

Yes. I couldn't find the paper.

**Comment by DominiqueMakowski** [comment]
You can find more details in this discussion here https://github.com/neuropsychology/NeuroKit/issues/245

The current default method has been written by @JanCBrammer but afaik there is not yet a citation available that validates this algorithm in particular (though for now you can cite [biopeaks](https://github.com/JanCBrammer/biopeaks) and neurokit)

**Comment by JanCBrammer** [comment]
See JanCBrammer/biopeaks#23.
