### ISSUE TITLE
ECG_Quality of ecg_process

### ISSUE THREAD

**Issue by alexxony** [neuropsychology/NeuroKit#482]
**Question and context**
I would like to use ECG_Quality of ecg_process as criteria of motion artifact.
So I tried to find exact meaning of ECG_Quality. 
How it calculate the value and threshold between good and bad signal?

**Comment by zen-juen** [comment]
Hi @alexxony you can read the documentation of `ecg_quality` over [here](https://neurokit2.readthedocs.io/en/dev/functions.html#neurokit2.ecg.ecg_quality) which includes the references regarding where the algorithms are extracted from, or take a look at the [source code](https://neurokit2.readthedocs.io/en/dev/_modules/neurokit2/ecg/ecg_quality.html#ecg_quality) to see the exact computations.
