### ISSUE TITLE
Respiratory Volume per Time (RVT)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#495]
Used to detect atypical breathing events, useful in the context of noise removal.

Methods:

- [x] [Birn et al., 2006](http://mriquestions.com/uploads/3/4/5/7/34572113/birn_separating_respirator.pdf)
- [x] [Harrison et al., 2021](https://www.sciencedirect.com/science/article/pii/S1053811921000641)

Resources & Implementations:

- https://github.com/physiopy/phys2denoise

**Comment by shanelindsay** [comment]
RVT would be good to have. 

Just to follow up on those links from Dominique:

The Harrison et al. Hilbert method matlab code is here:
https://github.com/translationalneuromodeling/tapas/blob/master/PhysIO/code/model/tapas_physio_rvt_hilbert.m

More straightforward to integrate would be the python code available here:
https://github.com/physiopy/phys2denoise/blob/master/phys2denoise/metrics/chest_belt.py

Which implements Envelope and RV (respiratory variability).

For noise removal, something like this would also be nice:
https://peakdet.readthedocs.io/en/latest/user_guide/editing.html
