### ISSUE TITLE
graph plotting not working any more

### ISSUE THREAD

**Issue by shashanka300** [neuropsychology/NeuroKit#496]
signal_plot function dosent plot any more 

Example from pipy

import numpy as np
import pandas as pd
import neurokit2 as nk

# Generate synthetic signals
ecg = nk.ecg_simulate(duration=10, heart_rate=70)
ppg = nk.ppg_simulate(duration=10, heart_rate=70)
rsp = nk.rsp_simulate(duration=10, respiratory_rate=15)
eda = nk.eda_simulate(duration=10, scr_number=3)
emg = nk.emg_simulate(duration=10, burst_number=2)

# Visualise biosignals
data = pd.DataFrame({"ECG": ecg,
                     "PPG": ppg,
                     "RSP": rsp,
                     "EDA": eda,
                     "EMG": emg})
nk.signal_plot(data, subplots=True)

It dosent plot the results

**Comment by zen-juen** [comment]
Hi @shashanka300 could you please elaborate on this and give us a reproducible example so that we can investigate?

**Comment by shashanka300** [comment]
> Hi @shashanka300 could you please elaborate on this and give us a reproducible example so that we can investigate?

**Comment by shashanka300** [comment]
> Hi @shashanka300 could you please elaborate on this and give us a reproducible example so that we can investigate?

**Comment by shashanka300** [comment]
sorry closed by mistake, kindly run the example, apparently the plot function has stoped working

**Comment by zen-juen** [comment]
No worries! What's your neurokit version? Can you also show us what is the error message you encountered?

**Comment by shashanka300** [comment]
> No worries! What's your neurokit version? Can you also show us what is the error message you encountered?

<img width="523" alt="Screenshot 2021-08-19 at 2 23 39 PM" src="https://user-images.githubusercontent.com/31235289/130039573-98eb7ae2-6f38-4e39-93f7-31165319f719.png">

normally post execution i used to get graphs, now nothing comes no error either

**Comment by zen-juen** [comment]
Are you using jupyter notebook as your IDE? You might need a `%matplotlib inline` at the start to see plots in your interface (see [more options](https://medium.com/@Med1um1/using-matplotlib-in-jupyter-notebooks-comparing-methods-and-some-tips-python-c38e85b40ba1))

**Comment by Manthan-tech** [comment]
Is there any solution for this, I am facing the same issue with the latest version. Nothing is happening on running signal_plot, ecg_plot, event_plot function

**Comment by shashanka300** [comment]
simple solution use plt.show() EOL

**Comment by Manthan-tech** [comment]
> simple solution use plt.show() EOL

My bad.., Thanks it worked😅
