### ISSUE TITLE
Downloading datasets using `mne_data` may need specified path

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#497]
Was playing around with mne and realized an error with `mne.datasets.sample.data_path()` used in our `mne_data()` function to access their datasets.

Can't remember if this used to work for me 🤔  but similar to this [issue](https://github.com/mne-tools/mne-python/issues/8764), seems like the function won't work if the data folder is not present - as in the case for me now, where I had to specify a specific path like so `mne.datasets.sample.data_path("C:/Users/Zen Juen/OneDrive/Desktop")` in order to download and access the datasets. 

For users who encounter this same error, perhaps we'll need a `path` argument in the `mne_data` function to get past this:

https://github.com/neuropsychology/NeuroKit/blob/a4eb198b75cd343a35a02af41f6bc32808442585/neurokit2/eeg/mne_data.py#L3-L15

**Comment by DominiqueMakowski** [comment]
indeed, probably needs a fix or perhaps at least catch the error and throw an informative error message?
