### ISSUE TITLE
Error when computing nonlinear HRV parameters

### ISSUE THREAD

**Issue by richrobe** [neuropsychology/NeuroKit#511]
When calling `nk.hrv_nonlinear()` on a particular array containing R peak location indices I get a `ZeroDivisionError` that originates from the `nk.complexity.fractal_higuchi()` function. The R peaks look reasonable, so I can't really explain why this error occurs?

The neurokit version is 0.1.4.
Here's the code to reproduce the error (the [csv file](https://github.com/neuropsychology/NeuroKit/files/7046497/rpeaks_bug_higuchi.csv) is attached)
```python
import pandas as pd
from neurokit2.complexity.fractal_higuchi import fractal_higuchi 

data = pd.read_csv("rpeaks_bug_higuchi.csv")
hrv_nonlinear(data, sampling_rate=256)
```

**Comment by Tam-Pham** [comment]
I will look at this asap. Thanks for the reproducible script!
