### ISSUE TITLE
Quick examples seem to be full of errors

### ISSUE THREAD

**Issue by Luo-XiuFeng** [neuropsychology/NeuroKit#514]
My Python environment:
![image](https://user-images.githubusercontent.com/45417928/131081229-c927d58c-b462-4db2-99fe-55d73ff3084a.png)
I ran the following example:
![image](https://user-images.githubusercontent.com/45417928/131081261-fcc47bfb-de99-4665-ace1-e8c185953774.png)
Instead of showing any graphics, it showed a bunch of errors:
![image](https://user-images.githubusercontent.com/45417928/131081349-fac01ea7-a34f-4ff8-b723-1d3b47c36875.png)
How to solve it?

In addition, running this example, although there is no error, there is no image, what is wrong?
![image](https://user-images.githubusercontent.com/45417928/131081548-0b007d98-76d2-4a4a-8ccd-6c88d9ea5d37.png)

**Comment by Luo-XiuFeng** [comment]
> Hi @LXiuFeng, what is the IDE (e.g., spyder, jupyter...) you are using? Also, what is your `matplotlib` version?
Can you tell me how to avoid mistakes?For example, run the following:
![image](https://user-images.githubusercontent.com/45417928/131469778-b6fe43d9-bef0-4014-8ff4-694a426b864c.png)

I will receive the following error on vscode：
![image](https://user-images.githubusercontent.com/45417928/131469902-44bf7a9d-51b1-4d45-8ad9-6c429cee2d7e.png)

**Comment by zen-juen** [comment]
Based on a quick check, looks like you may have to update `matplotlib` to the latest version (3.4.3), as it seems like this issue was mentioned in [the 3.3.1 release](https://github.com/matplotlib/matplotlib/pull/18101). Could you try that and let us know?

**Comment by Luo-XiuFeng** [comment]
> Based on a quick check, looks like you may have to update `matplotlib` to the latest version (3.4.3), as it seems like this issue was mentioned in [the 3.3.1 release](https://github.com/matplotlib/matplotlib/pull/18101). Could you try that and let us know?

你好，我已经测试，因为我的python是3.6，无法指定安装到3.4.3，但可以安装到3.3.4，我重新测试了示例，完美的运行，没有任何错误，谢谢
