### ISSUE TITLE
HRV computation crashes for "no" heart rate variability

### ISSUE THREAD

**Issue by richrobe** [neuropsychology/NeuroKit#533]
Hey guys,

I'm currently working with ECG data from patients that have (little to) no HRV and wanted to compute continuous time-domain HRV metrics over sliding windows. For windows that have constant heart rate the `nk.hrv_time()` function crashes with an `IndexError` when trying to compute the TINN metric. 

I'm using neurokit version 0.1.4.1 and here's a code snippet to reproduce:
```python
rpeaks = np.arange(0, 2049, step=128)
# this crashes with an IndexError
nk.hrv_time(rpeaks, sampling_rate=256)
```

This error vanishes when as soon as any RR interval in the window is not the same anymore:
```python
rpeaks = np.arange(0, 2049, step=128)
# change any arbitrary R peak index
rpeaks[1] += 1
# this won't crash anymore
nk.hrv_time(rpeaks, sampling_rate=256)
```

An easy fix would be to check for this `IndexError` and return NaN for this metric, for example, like this (starting at l. 196 of `hrv_time.py`):
Change:
```python
n = bar_x[np.where(bar_x - np.min(rri) > 0)[0][0]]  # starting search of N
```
to:
```python
    idx_where = np.where(bar_x - np.min(rri) > 0)[0]
    if len(idx_where) == 0:
        return np.nan
    n = bar_x[idx_where[0]]  # starting search of N
```

If you agree with my suggestion I'm happy to make a pull request for this fix :)

Best,
Robert

**Comment by DominiqueMakowski** [comment]
> I'm happy to make a pull request

By all means please do :)
