### ISSUE TITLE
Bug in nk.complexity_delay() with  method="casdagli1991"

### ISSUE THREAD

**Issue by zeydabadi** [neuropsychology/NeuroKit#544]
This is a template for reporting a bug. You can remove it and write from scratch. These sections are a rough guide, but the important thing is to give enough details so that the developers can **reproduce** the bug on their machine and then investigate.

**Describe the bug**
If "delay_max" set to a number for which the algorithm can't find a zero crossing, then nk.complexity_delay() crashes.
`nk.complexity_delay(signal, delay_max=20, show=False, method="casdagli1991")`
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_283889/3788459661.py in <module>
----> 1 nk.complexity_delay(signal, delay_max=20, show=False, method="casdagli1991")

~/Downloads/general/lib/python3.9/site-packages/neurokit2/complexity/complexity_delay.py in complexity_delay(signal, delay_max, method, show)
    114 
    115     # Get optimal tau
--> 116     optimal = _embedding_delay_select(metric_values, algorithm=algorithm)
    117     optimal = tau_sequence[optimal]
    118 

~/Downloads/general/lib/python3.9/site-packages/neurokit2/complexity/complexity_delay.py in _embedding_delay_select(metric_values, algorithm)
    136         optimal = signal_zerocrossings(metric_values)[0]
    137     elif algorithm == "first zero crossing":
--> 138         optimal = signal_zerocrossings(metric_values)[0]
    139     elif algorithm == "closest to 40% of the slope":
    140         slope = np.diff(metric_values) * len(metric_values)

IndexError: index 0 is out of bounds for axis 0 with size 0
`

**To Reproduce**
Example steps to reproduce the behavior. For instance:
THE ERROR IS REPORTED ABOVE. ALL YOU NEED TO REPRODUCE IT IS TO HAVE A SIGNAL THAT DOES NOT HAVE A ZERO CROSSING FOR A GIVEN MAX_DELAY.

**Expected behavior**
The function should raise an error with a description of why this happened and with an option to not crash and continue if that's what the user wants. In this case, the output of the function could be NaN so at the end the user knows where something went wrong.

**Screenshots**
If applicable and useful, you can add screenshots by drag-and-dropping the images in the issue window.

**System Specifications**

It's important that you give us some information about the system you are using. For that you can run:

`- OS: Linux (ELF 64bit) 
- Python: 3.9.6 
- NeuroKit2: 0.1.4.1 

- NumPy: 1.21.1 
- Pandas: 1.3.0 
- SciPy: 1.7.1 
- sklearn: 0.23.2 
- matplotlib: 3.4.2`

**Comment by Tam-Pham** [comment]
Thanks for raising the issue @zeydabadi 

I do agree with you that the expected behaviours should be a warning and a nan output :) it's a quick fix I will follow up asap.
