### ISSUE TITLE
EMG fail to process a specific signal (KeyError)

### ISSUE THREAD

**Issue by froynard** [neuropsychology/NeuroKit#563]
Hello,
I'm currently using your library for my project.

I'm trying to use the emg module to procees a signal but i get a weird error when i call the emg_process fuction.

here is the repro code:

```python

import numpy as np
import neurokit2 as nk

data_dumped = np.loadtxt(r'signal_failed.csv')
print('signal size : {}'.format(len(data_dumped)))    # print: signal size: 3500
signals_emg, info_emg = nk.emg_process(data_dumped, 700)

```

I get the following error:

```bash
KeyError: '[3500] not in index'
```

when I feed a signal whose size is 3500 (I've attached the signal that repro the bug to this issue: [signal_failed.csv](https://github.com/neuropsychology/NeuroKit/files/7400509/signal_failed.csv)).

Is there a bug in the library? Or am I missing something when using it?

Thank you for your feedbacks.
Fabien.

**Comment by DominiqueMakowski** [comment]
That's very strange. My pandas is 1.3.3, so even older than you.

From the tracelog the error originates from signal_formatpeaks, which fails to correctly deal with the input type.

Could you try this:

```python
import numpy as np
import neurokit2 as nk
import pandas as pd

data_dumped = pd.read_csv(r'signal_failed.csv', names=["EMG"])
signals_emg, info_emg = nk.emg_process(data_dumped["EMG"], 700)
```

**Comment by froynard** [comment]
Hello,

Thanks it fixes the issue
