### ISSUE TITLE
No method to find onset of PPG

### ISSUE THREAD

**Issue by abhinandanpanda** [neuropsychology/NeuroKit#590]
Hi Sir,
I am trying to analyze PPG signal and to extract onset and peaks. With the existing methods supplied with this tool, I am able to find only peaks  but not onset of PPG. 

As I am new to signal processing, any help would be really appreciated.

Regards
Abhinandan

**Comment by DominiqueMakowski** [comment]
Hi, currently we don't have a "delineator" for PPG. If you manage to find some implementations or make your own, feel free to let us know and contribute here

**Comment by danibene** [comment]
Maybe this implementation could be a starting point: https://github.com/qiriro/PPG/blob/master/ppg/feature.py
