### ISSUE TITLE
RPeaks are calculated twice in ecg_process

### ISSUE THREAD

**Issue by CReizner** [neuropsychology/NeuroKit#602]
Within the function **ecg_process**, you are calculating rpeaks with **ecg_peaks** but do not pass it to the **ecg_quality** function and **_ecg_quality_averageQRS** will therefore calculate the rpeaks list again. 

```
def ecg_process(ecg_signal, sampling_rate=1000, method="neurokit"):
    ...
    instant_peaks, rpeaks, = ecg_peaks(
        ecg_cleaned=ecg_cleaned, sampling_rate=sampling_rate, method=method, correct_artifacts=True
    )
    ...
    quality = ecg_quality(ecg_cleaned, !!!rpeaks=None!!!, sampling_rate=sampling_rate)
    ...
```

**Comment by zen-juen** [comment]
Hi @CReizner thanks for catching this! Indeed you're right, it should be `rpeaks=rpeaks` rather than `rpeaks=None` in `ecg_process` to avoid peak computation again. Would you like to open a [pull request](https://github.com/neuropsychology/NeuroKit/compare) to the dev branch here?

**Comment by CReizner** [comment]
Hi @zen-juen. It should be  ```rpeaks=rpeaks['ECG_R_Peaks']```, because it wants a list. I honestly don't know how git or github works, so I don't see myself creating a pull request =D

**Comment by DominiqueMakowski** [comment]
No worries, we'll fix it then. Thanks a lot for letting us know!
