### ISSUE TITLE
heart rate from ECG

### ISSUE THREAD

**Issue by talhaanwarch** [neuropsychology/NeuroKit#614]
**Question and context**
I have data from 6 channels/leads ['lead1','lead2','lead3','avr','avL','avf'], each lead has an array how  calculate the heart rate from it.
thanks

**Comment by DominiqueMakowski** [comment]
Hi, sorry for the late reply. I suggest you take a look at lead 1 which should usually display positive R-peaks. You can pass this channel to the various `ecg_*` functions such as `ecg_process()`
