### ISSUE TITLE
MNE 1.0: adjustments

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#626]
```python
import neurokit2 as nk
import mne

raw = mne.io.read_raw_fif(
        mne.datasets.sample.data_path() + "/MEG/sample/sample_audvis_raw.fif", preload=True
    )
x = nk.mne_channel_extract(raw, what="EOG", name="EOG")
x
```

This used to return a vector (I think?), but now it returns a series (at least based on the bug in the test that caught this)

TODO: need to investigate `mne_channel_extract()` and see if changes are to be made based on the most recent MNE update

**Comment by JoseAlanis** [comment]
Hi, is this still an issue, I could take a look 😃

**Comment by DominiqueMakowski** [comment]
I "think" it has been solved? since we don't have tests failing at least... But if they are other MNE-related things (and there will be, as enhancing the M/EEG aspect of NK is one of the goals), I'll let you know :)

btw, great job on the MNE-LIMO toolbox
