### ISSUE TITLE
`eda_plot` throws ValueError when the number of onsets is not the same as the number of peaks

### ISSUE THREAD

**Issue by Rvb0rob0t** [neuropsychology/NeuroKit#632]
**Describe the bug**
`eda_plot` throws `ValueError` when the number of onsets is not the same as the number of peaks because of the sentence
https://github.com/neuropsychology/NeuroKit/blob/c1104386655724a5c624e740abf651c939fc5e48/neurokit2/eda/eda_plot.py#L114

**To Reproduce**

1. Get a signal with a peak without an onset, like
```
[0.0,
 0.180624,
 0.217774,
 0.25108,
 0.228022,
 0.226741,
 0.226741,
 0.219055,
 0.217774,
 0.21265]
```
2. Process it without cleaning like in #554 (I'm also using an Empatica E4)
3. Try to plot the resulting signals with `eda_plot()`

**Expected behaviour**
I would expect one of the following:
- that in this case, eda_plot would simply not plot the first onset.
- that it warns that the specific fact that there is a peak without an onset is a problem.

**System Specifications**
- OS: Linux (ELF 64bit) 
- Python: 3.10.2 
- NeuroKit2: 0.1.7 

- NumPy: 1.22.3 
- Pandas: 1.4.1 
- SciPy: 1.8.0 
- sklearn: 1.0.2 
- matplotlib: 3.5.1

**Comment by DominiqueMakowski** [comment]
> that in this case, eda_plot would simply not plot the first onset.

Yes we should go ahead with this option, I don't think there is a need for a warning.

Would you mind opening another PR with a fix? Thanks a lot!
