### ISSUE TITLE
ecg_peak function return wrong result

### ISSUE THREAD

**Issue by farmboy-dev** [neuropsychology/NeuroKit#636]
Hi 

Thank you for the Great project!

I have a ECG dataset (500Hz, 10s). 
![image](https://user-images.githubusercontent.com/70833564/161895167-84c194ae-3f6d-4789-8f89-c118b27109f4.png)

How to solve it? 

Thank you!

**Comment by DominiqueMakowski** [comment]
you could try using a different `method`. But in general the signal at the edges of recordings are difficult to analyze (that's why whenever recording, you should wait a few seconds after starting the recording before starting a task of interest)

**Comment by farmboy-dev** [comment]
Thank you!
