### ISSUE TITLE
How to access to the source code of eda processing functions ?

### ISSUE THREAD

**Issue by Mikinox3** [neuropsychology/NeuroKit#639]
Hi everyone, I am new on github and definitely new in coding and I'd like to access the _eda_clean_ and _eda_process_ functions' source code to understand how my dataset is filtered. I spent some time looking in many files here but didn't find any information regarding my issue. Does anyone know how to access to the source code or how to send a request for the access if needed ?

thank you very much !

**Comment by DominiqueMakowski** [comment]
Hi @Mikinox3 and welcome to github! You can find the function definition at https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/eda/eda_clean.py (in the neurokit2/eda folder)
