### ISSUE TITLE
Error in calculation of breathing amplitude in rsp_rate()

### ISSUE THREAD

**Issue by JohnDoenut** [neuropsychology/NeuroKit#64]
https://github.com/neuropsychology/NeuroKit/blob/fe257bbb565cbf0d397e1d61c16dce06d3b64f8a/neurokit2/rsp/rsp_rate.py#L108-L111

We currently return breathing period instead of breathing amplitude from `rsp_rate()`. Also visible here (compare the y-axis scale of the first and last plot and also note how the second and last plot contain very similar information).

https://github.com/neuropsychology/NeuroKit/blob/master/docs/img/README_respiration.png?raw=true

Fixing this requires a bit of refactoring, since the calculcation of breathing amplitude requires both the raw breathing signal and the breathing extrema. Currently, we only have access to the extrema in `rsp_rate()`.

We could return the signal value at the extrema alongside the extrema in `rsp_findpeaks()` in order to fix this. @DominiqueMakowski, what are your thoughts?

**Comment by JohnDoenut** [comment]
@DominiqueMakowski , maybe it's easiest to have a dedicated rsp_amplitude() function in the rsp module. Calculating breathing amplitude inside `rsp_rate()` is going to be somewhat awkward and clumsy.

**Comment by DominiqueMakowski** [comment]
> maybe it's easiest to have a dedicated rsp_amplitude() function in the rsp module. Calculating breathing amplitude inside rsp_rate() is going to be somewhat awkward and clumsy.

Agreed, it could be more specific and its own dedicated parameters

**Comment by JohnDoenut** [comment]
I'm going to fix this after the PR for the ecg module.

**Comment by JohnDoenut** [comment]
Closing this after #68
