### ISSUE TITLE
Strategies for denoising ECG signal recorded in MRI settings

### ISSUE THREAD

**Issue by sangfrois** [neuropsychology/NeuroKit#644]
### After several exchanges between well-minded researchers working with biosignals, I come with a concrete suggestion to merge forces 
Since I started my master's, I've been wanting to increase accessibility of biosignal processing techniques for MRI settings. [Katie Bottenhorn](https://github.com/62442katieb) and I have been meeting regularly to push this forward. We work with the [physiopy community](https://github.com/physiopy) primarily for developing data curation and standardization methods, but we are also individually involved in the creation of different (but majorly overlapping) full biosignal data preparation pipelines. I feel like a lot of the job i've done has been done by others. So we would like to  take the opportunity to push a single and concise aspect of our work, believing it would help people in the same situation as us. 

Also, after years of discussions with institutional authorities regulating the project I'm working on ([Courtois-NeuroMod](https://docs.cneuromod.ca/en/2020-alpha/MRI.html#physiological-measures)), my supervisor finally obtained the green light to publicly share rolling releases of ongoing data collection. This means hundreds of hours of biosignal data will be made available to the scientific community. This would eventually allow us to benchmark our ECG denoising technique.

## Our solution is essentially to add a workflow to ``ecg_clean()`` function
This would allow researchers to apply a "magnetic filed gradients denoising" technique to their ECG processing workflow. The way we've tackled the problem was by translating the BIOPAC recommendation notes to python. Katie, then, applied their logic to multiband, multi-echo recordings (here's her [paper](https://www.biorxiv.org/content/10.1101/2021.04.01.437293v1)). Instead of having project-specific scripts to denoise such data, it would be awesome to have a standardized one-liner function in NeuroKit2 that does everything. I believe this would help researchers to feel more inclined to record ECG signals in MR environments. The workflow could be easily used in other projects pushed forward by physiopy.

## How could we do it?
This would require us to synthesize [Katie's work](https://github.com/62442katieb/mbme-physio-denoising) and [mine](https://github.com/sangfrois/ds_prep/tree/dev/physio). As you can see in my [scripts](https://github.com/sangfrois/ds_prep/blob/dev/physio/preproc/neuromod_clean.py), I've already adopted the coding scheme utilized in NeuroKit2. So, most of the work is done. We would still have to think about the optimal way of probing users' sequence specs and trigger channel to compute the "comb-bandpass filtering" technique, but it's manageable.

Tell us what you think. I could right up a PR  in the coming week(s)
This is def not at the top of our prioriy list, but it's most def an important push for embodied neuroscience to takeover brainocentric MR settings.

**Comment by DominiqueMakowski** [comment]
Hey @sangfrois, hope you're doing great

Sounds awesome!! feel free to start a PR whenever you want :)
