### ISSUE TITLE
Finding QRS onset and offset

### ISSUE THREAD

**Issue by OmkarPathak** [neuropsychology/NeuroKit#648]
Hi,
Is there a way in which we cam find the QRS onset and offset. I want to determine the QRS width using this package but am not able to do so.
Q,R and S peaks are detected correctly but I cannot get a way to find Q onset and offset. Any suggestions would be helpful.

**Comment by levsilva** [comment]
Hi @OmkarPathak,

I believe the "ECG_R_Onsets" and "ECG_R_Offsets" from the "ecg_delineate" function are the fiducial points you are looking for. Look at the figure generated by the method here: https://neuropsychology.github.io/NeuroKit/examples/ecg_delineate/ecg_delineate.html.

Hope it helps.

**Comment by DominiqueMakowski** [comment]
thanks @levsilva for helping the community, much appreciated ☺️ 

additionally @OmkarPathak, you can also try delineating with other method (e.g., [cwt](https://neuropsychology.github.io/NeuroKit/examples/ecg_delineate/ecg_delineate.html#continuous-wavelet-method-cwt)). However if you're signal is too noisy it is possible that the onsets / offsets of each wave won't be correctly detected.
