### ISSUE TITLE
Error: the function of hrv_nonlinear(): window cannot contain more data points than the time series

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#657]
Hello, 

How can I deal with the error after running following code?

```
analyze_epochs_inter = nk.ecg_intervalrelated(epochs)
```

Thank you in advance!

![image](https://user-images.githubusercontent.com/58549690/173239307-682c68ce-40bc-4c3e-a688-c962508a5086.png)

**Comment by DominiqueMakowski** [comment]
The error seems to originate from `hrv_nonlinear()`. Can you run that function alone and paste the error log? thanks

**Comment by RyotaTKN** [comment]
Here is the error by using ```hrv_nonlinear```. (Sorry for small pic)

<img width="405" alt="image" src="https://user-images.githubusercontent.com/58549690/173265175-3e8b43ff-712e-4d07-9556-419706feb3fe.png">

**Comment by DominiqueMakowski** [comment]
you need to do something like:

```python
for i in epochs:
    peaks = nk.ecg_peaks(epochs[i])
    nk.hrv_nonlinear(peaks)
```

**Comment by RyotaTKN** [comment]
Here is the error from the code.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/58549690/173266215-11f0a82c-2c2f-46fc-b3a7-7e06c4b8d517.png">

**Comment by DominiqueMakowski** [comment]
How long are your epochs? If there are only a few seconds, I'd suggest using `ecg_eventrelated()` rather than `ecg_intervalrelated()`. The error seems to indicate that the epochs are too short to compute DFA.

That said, I will add a safety-pass so that the function doesn't error

**Comment by RyotaTKN** [comment]
The ECG is measured during 100 games, with a time range of 3 to 60 seconds per game.
I would like to somehow extract HRV-related indicators, but is this difficult?

Here is the event table. (sampling_rate = 1000)
<img width="97" alt="image" src="https://user-images.githubusercontent.com/58549690/173268083-9a40291e-8ea0-4e71-a348-a3661128caba.png">

**Comment by DominiqueMakowski** [comment]
3 seconds is definitely too short (even 60 seconds) for many of the HRV indices. If you really want to compute something, I would really solely on basic time-domain indicators like RMSSD. Thus I'd recommend only using `hrv_time()`. But there will likelky be a huge effect of the epoch duration.

**Comment by RyotaTKN** [comment]
Thank you! I will use hrv_time then.
