### ISSUE TITLE
Attributing the 'Martinez2003' ECG R-peak detection algorithm

### ISSUE THREAD

**Issue by peterhcharlton** [neuropsychology/NeuroKit#700]
**Problem**
There is currently no attribution for the 'Martinez2003' ECG R-peak detection algorithm provided in the `_ecg_findpeaks_WT` function, within the [`ecg_findpeaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_findpeaks.py) function.

**Suggestion**
I think the 'Martinez2003' algorithm is an implementation of the algorithm described in the following paper:
_[Martínez JP, Almeida R, Olmos S, Rocha AP, Laguna P. A wavelet-based ECG delineator: evaluation on standard databases. IEEE Trans Biomed Eng 2004;51:570–581.](https://doi.org/10.1109/TBME.2003.821031)_
This is because the implemented algorithm finds R-peaks using:
- a 1st order Gaussian derivative wavelet transform (see [here](https://pywavelets.readthedocs.io/en/latest/ref/cwt.html?highlight=cwt#gaussian-derivative-wavelets) and Section II.B of the paper)
- scales 2^1 - 2^4 (which is in keeping with those used in Section II.D(1) of the paper)
- change from a negative minimum to a positive maximum (which is similar to the "positive maximum-negative minimum pair" used in Section II.D(1) of the paper).

**Resolution**
- I think mentions of 'Martinez2003' could be replaced with 'Martinez2004' in the following:
   - [`ecg_findpeaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_findpeaks.py)
   - [`ecg_peaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_peaks.py)
- I think the following comment in [`ecg_findpeaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_findpeaks.py) could be updated from 2003 to 2004:
```
# =============================================================================
# Continuous Wavelet Transform (CWT) - Martinez et al. (2003)
# =============================================================================
```
- I think the following documentation provided in [`ecg_peaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_peaks.py) could be updated from:
```
    * ``martinez2003``
        **Unknown.** Please help us retrieve the correct source!
```
   to:
```
    * ``martinez2004``
        * Martínez, J. P., Almeida, R., Olmos, S., Rocha, A. P., & Laguna, P. (2004) A wavelet-based ECG delineator: evaluation on standard databases. IEEE Trans Biomed Eng, 51(4), 570–581.
```

I'll be happy to raise a pull request for this.

**Comment by DominiqueMakowski** [comment]
Good catch! Please don't hestitate to open a PR :)

**Comment by peterhcharlton** [comment]
Great thanks - now opened [PR 702](https://github.com/neuropsychology/NeuroKit/pull/702)

**Comment by peterhcharlton** [comment]
Thanks for your help with this - I hadn't realised that the tests would need updating too, which @DominiqueMakowski has now done in [PR 702](https://github.com/neuropsychology/NeuroKit/pull/702).
