### ISSUE TITLE
Expected output of R-R interval detrending with tarvainen2002 method

### ISSUE THREAD

**Issue by danibene** [neuropsychology/NeuroKit#721]
**Question and context**

I noticed that there seems to be an artifact at the end of the R-R interval signal when detrending with the `tarvainen2002` method. See the plot at the end of this notebook: https://gist.github.com/danibene/ecc05a282e93dcd6f55b877e21f69281 

Any idea if this is the expected output?

**Comment by DominiqueMakowski** [comment]
🤔 no idea

**Comment by danibene** [comment]
I tried plotting the same thing with the modifications made in https://github.com/neuropsychology/NeuroKit/pull/569 and the result looks more reasonable to me: https://gist.github.com/danibene/e9fecdce9cced55628c53db1d93c2830

**Comment by DominiqueMakowski** [comment]
I'm closing that, but feel free to reopen
