### ISSUE TITLE
ECG R-Peak detection using visibility graphs

### ISSUE THREAD

**Issue by sokolmarek** [neuropsychology/NeuroKit#744]
**Describe the solution you'd like**
I recently came across a new algorithm for detecting R peaks that I found very interesting and I haven't seen it anywhere before. The algorithm uses a time series to visibility graph transformation. The cool thing is that it has linear complexity and it could also be useful for preprocessing in HRV analyses, as it is more robust to outliers. The authors benchmarked the method on the GUDB database against other SWTs (e.g. Kalidas 2017) and matched filter QRS detectors. The performance difference compared between the methods seems quite diametric to me. So I thought it was interesting enough that it would be nice to implement this method within the Neurokit2 library. Below I attach a reference to the corresponding article.

- [T. Koka and M. Muma, "Fast and Sample Accurate R-Peak Detection for Noisy ECG Using Visibility Graphs," 2022 44th Annual International Conference of the IEEE Engineering in Medicine & Biology Society (EMBC), 2022, pp. 121-126, doi: 10.1109/EMBC48229.2022.9871266.](https://ieeexplore.ieee.org/document/9871266)

**How could we do it?**
I have already implemented the method for my own purposes with the compatibility of the latest version of the [ts2vg](https://pypi.org/project/ts2vg/) library. In the attached article they have everything nicely described. Eventually, I would create a pull request and redo my implementation according to neurokit conventions:)

**Comment by DominiqueMakowski** [comment]
Hi Marek! 

That's very interesting, I wasn't aware of the visibility graph concept. Exciting!
By all means, do open a PR, and we'll assist you with the implementation :)
