### ISSUE TITLE
ecg_peaks() method=""

### ISSUE THREAD

**Issue by nileshkrsahu** [neuropsychology/NeuroKit#751]
**Question and context**
In the reference given on the neuorkit website, the paper by Gutiérrez-Rivas("Gutiérrez-Rivas, R., García, J. J., Marnane, W. P., & Hernández, A. (2015). Novel real-time low-complexity QRS complex detector based on adaptive thresholding. IEEE Sensors Journal, 15(10), 6036-6043." ) was cited, but I didn't find any method for this.

**Comment by DominiqueMakowski** [comment]
Hi @nileshkrsahu, could you help us link to where we mentioned that paper?

**Comment by nileshkrsahu** [comment]
Here is the link: https://neuropsychology.github.io/NeuroKit/functions/ecg.html#ecg-peaks
In references of ecg_peaks (Reference 14)

**Comment by DominiqueMakowski** [comment]
@levsilva if I'm not mistaken you recently sanitized a bit all the ECG-peak detection references and all that, would you know something here?

**Comment by levsilva** [comment]
Hi @DominiqueMakowski and @nileshkrsahu,

@nileshkrsahu In the file `ecg_findpeaks.py`, you will find comments within each hidden function of individual peak finders, referring to the papers related to them. The function for the method `rodrigues2021` has a comment saying it was inspired by on _Gutierrez-Rivas (2015)_ and _Sadhukhan (2012)_ papers. So those two papers are related to this method.

@DominiqueMakowski In fact, I have updated the doc for ecg_peaks.py, pooling and itemizing all paper related to each method. Maybe some have updated it after me?
