### ISSUE TITLE
Multiscale entropy -- backwards compatibility with an earlier version?

### ISSUE THREAD

**Issue by williamgilpin** [neuropsychology/NeuroKit#760]
Hello, thank you so much for this fantastic tool!

I used neurokit2 to compute multiscale entropy for a recent [dataset of dynamical systems](https://github.com/williamgilpin/dysts). In the version of neurokit2 that I used, I computed the multiscale entropy for every system via

```
mmse_opts = {"composite": True, "refined": False, "fuzzy": True}
neurokit2.complexity.entropy_multiscale(sol, dimension=2, **mmse_opts)
```

I want to perform the same calculation with the new version of the function. What do I need to do to perform the exact same calculation as I ran before? I tried using the following, but it doesn't quite seem to be the same:

```
mmse_opts = {"composite": True, "fuzzy": True}
mmse = neurokit2.entropy_multiscale(sol, dimension=2, **mmse_opts)[0]
```

The reason that I want to replicate the earlier version is to avoid re-computing the entropy for every dataset in my database---I'd rather only compute it for new systems going forward.

Thanks very much!

**Comment by DominiqueMakowski** [comment]
As we re-implemented and revised most of the complexity internal machinery, we fixed many things, which could lead to some discrepancies between versions. As much as I understand it is annoying to re-compute them, I would tend to trust the new results more.

If you really want reproducibility, you can downgrade to an earlier version, e.g.,

```
pip install --force-reinstall -v "neurokit2==1.5"
```

Hope that helps!
