### ISSUE TITLE
Incorrect edges of peak waves

### ISSUE THREAD

**Issue by okovalchuk98** [neuropsychology/NeuroKit#761]
Hello,
I tried to use NeuroKit to detect edges of peaks (waves) of ECG signal. I understood from the [documentation sample](https://neuropsychology.github.io/NeuroKit/examples/ecg_delineate/ecg_delineate.html#continuous-wavelet-method-cwt) that the ECG_R_Onsets and ECG_R_Offsets match the edge of QRS complexes
I did some experiments and received different results.

**Experiment** 1
Input: the '100' signal of [MIT-BIH Arrhythmia Database](https://physionet.org/content/mitdb/1.0.0/)
![image](https://user-images.githubusercontent.com/38636278/213533565-49a0bd25-6d75-4e79-94cb-3bf030bc3980.png)
_Comment_: location of ECG_R_Onset and ECG_R_Offset is as expected.

**Experiment** 2
Input: the '109' signal of [MIT-BIH Arrhythmia Database](https://physionet.org/content/mitdb/1.0.0/)
![image](https://user-images.githubusercontent.com/38636278/213535127-e58ba753-b4c2-49a8-8258-394804db8b2a.png)
_Comment_: The ECG_R_Onset is placed after the Q peak which is not correct. Also, you can see on the screenshot that P-Onset started before ECG_R_Offset which looks like a bug

The following fragment of code used to get wave's onset/offset

```python
        ecg_cleaned_signal = nk.ecg_clean(ecg_input_signal.origin_sinal, sampling_rate=ecg_input_signal.sampling_rate, method="biosppy")
        _, rpeaks = nk.ecg_peaks(ecg_cleaned_signal, sampling_rate=ecg_input_signal.sampling_rate)
        _, waves = nk.ecg_delineate(ecg_cleaned_signal, rpeaks, sampling_rate=ecg_input_signal.sampling_rate)
```

Could you please review this issue or clarify this behavior?

**Comment by DominiqueMakowski** [comment]
Did you try with other delineation methods?

**Comment by okovalchuk98** [comment]
> Did you try using other delineation methods?

yes. The 'dwt' delineation method is used in the initial post. I tied to use the 'cwt' delineation method and received worse result than for 'dwt'. The 'cwt' delineation method make following mistakes for the '109' signal of [MIT-BIH Arrhythmia Database](https://physionet.org/content/mitdb/1.0.0/)
1. Does not detect ECG_R_Offsets
2. The ECG_P and ECG_T wave detected in same place

![image](https://user-images.githubusercontent.com/38636278/213696001-03dba2aa-e562-4de3-bbd8-7a00c0c35603.png)

**Comment by danibene** [comment]
> The ECG_R_Onset is placed after the Q peak which is not correct.

To prevent this, maybe it would make sense to change the `_dwt_delineate_qrs_bounds()` to only select R_Onsets before the Q_Peaks, as follows:
https://github.com/danibene/NeuroKit/commit/2890732ede88a0e60af411b80c3e1ba768f254eb

**Comment by okovalchuk98** [comment]
yes, this issue is still actual

**Comment by HotDog702** [comment]
See also #809

**Comment by danibene** [comment]
Closing this as it was addressed in https://github.com/neuropsychology/NeuroKit/pull/815 , it should be resolved in the `dev` branch now, but feel free to reopen if necessary
