### ISSUE TITLE
Add different R-peaks detectors

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#77]
I think it would be useful to support different ECG segmenters and R-peaks detection algorithms (useful also for comparing them to base ourselves on the best).

@marianpetruk based on your [repo showing a comparison](https://github.com/marianpetruk/ECG_analysis) between different detectors, would you be interested in eventually copying and documenting some of them to neurokit2?

https://github.com/neuropsychology/NeuroKit/blob/c96702b68babe7bb747b13d142e4298ec9455780/neurokit2/ecg/ecg_findpeaks.py#L96-L101

Aside from biosppy, many of them are also implemented in [py-ecg-detectors](https://github.com/berndporr/py-ecg-detectors) (so we can cross-validate our implementations)

### Progress

- [x] Pan and Tompkins (1985)
- [x] Hamilton (2002)
- [x] Christov (2004)
- [x] [Gamboa (2008)](https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L834)
- [x] Elgendi et al. (2010)
- [x] Engzee Mod (Englese and Zeelenberg, 1979; Lourenço et al., 2012)
- [x] Kalidas and Tamil (2017)
- [x] [SSF - Zong et al., 2003](https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L448)
- [ ] [Modified SSF-TKE - Rankawat (2018)](https://ieeexplore.ieee.org/document/8527395)
- [ ] [R-DECO (Moeyersons et al., 2019)](https://peerj.com/articles/cs-226/)  [*(matlab)*](https://gitlab.esat.kuleuven.be/biomed-public/r-deco)
- [ ] [Aspuru et al. (2019)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6412424/)
- [ ] [Adaptive Median Filter (Bae et al. 2020)](https://www.mdpi.com/1424-8220/20/21/6144)

See also 
- [Porr & Howell, 2019, *R-peak detector stress test with a new noisy ECG database reveals significant performance differences amongst popular detectors*](https://www.biorxiv.org/content/10.1101/722397v3.full)
- [Liu et al., 2018, *Performance Analysis of Ten Common QRS Detectors on Different ECG Application Cases*](https://new.hindawi.com/journals/jhe/2018/9050812/)

**Comment by JohnDoenut** [comment]
@DominiqueMakowski, in the meantime we could already think about a testing framework akin to [wfdb](https://github.com/MIT-LCP/wfdb-python/blob/master/wfdb/processing/evaluate.py), maybe using `ecg_simulate()` instead of a database such as [MITDB](https://physionet.org/content/mitdb/1.0.0/) or [GUDB](http://researchdata.gla.ac.uk/716/). In any case, would be nice to have some principled way of comparing different detectors without depending on third party databases.
