### ISSUE TITLE
How to combine RRi and R-peak variation of ECG for a better EDR signal?

### ISSUE THREAD

**Issue by mobilemodem** [neuropsychology/NeuroKit#770]
I am trying to improve similarity of EDR signal to respiration signal.
I used two traditional method to get EDR signal:
1\ R-peak amplitude variation to get AM signal of thor respiration. Call EDR1 later.
2\ RRi to get RSA signal. Call EDR2 later.
I calculate the correlation between EDR and RESP signal on Fantasia database.
Some show good similarity on EDR1, Some on EDR2.
The best corrrelation value of EDR1 is 0.925, the worst is 0.041, averagely 0.67 on 40 files.
The best corrrelation value of EDR2 is 0.757, the worst is 0.171, averagely 0.451 on 40 files.
For file f2y05, r(EDR2|rsp) = 0.171, r(EDR1|rsp) = 0.741.
For file f2o02, r(EDR2|rsp) = 0.655, r(EDR1|rsp) = 0.041.

How can I decide the best EDR signal without resp signal for reference?
Higher sample rate means better EDR2.

2023-FEB-07
How can I upload the excel files of EDR results on Fantasia database and CEBSDB database(5 KHz sample rate)? 

The following result is for Fantasia database:
File_name | Rpeak_Num | EDR1-Corr | Time-Delay | EDR2-Corr | Time-Delay | EDR3-Corr | Time-Delay
-- | -- | -- | -- | -- | -- | -- | --
1o01 | 7180 | 0.622941878 | 22 | 0.508771804 | 33 | 0.844606814 | 22
1o02 | 6834 | 0.268539229 | 24 | 0.387751709 | 22 | 0.485276147 | 24
1o03 | 7229 | 0.779382183 | 17 | 0.425248717 | 29 | 0.84371209 | 18
1o04 | 6263 | 0.626204029 | 23 | 0.26238792 | 20 | 0.742333022 | 23
1o05 | 5767 | 0.741554911 | 22 | 0.286073264 | 36 | 0.804103107 | 22
1o06 | 6247 | 0.612186712 | 25 | 0.69384283 | 22 | 0.879357673 | 25
1o07 | 7156 | 0.412599777 | 22 | 0.582154605 | 20 | 0.746718008 | 22
1o08 | 8486 | 0.769416061 | 21 | 0.399180854 | 18 | 0.85767623 | 20
1o09 | 5413 | 0.152014069 | 23 | 0.12229295 | 21 | 0.265086488 | 21
1o10 | 8244 | 0.571002833 | 22 | 0.221593975 | 9 | 0.7168189 | 22
1y01 | 8706 | 0.524397972 | 22 | 0.599597604 | 17 | 0.859725658 | 22
1y02 | 7035 | 0.353965061 | 24 | 0.572486764 | 17 | 0.639936649 | 23
1y03 | 7640 | 0.732646371 | 20 | 0.535948378 | 15 | 0.736240994 | 21
1y04 | 5515 | 0.749706173 | 26 | 0.455782799 | 36 | 0.766657898 | 26
1y05 | 6979 | 0.711867663 | 16 | 0.426950062 | 30 | 0.719647637 | 16
1y06 | 7089 | 0.749524269 | 20 | 0.31248199 | 18 | 0.755660132 | 20
1y07 | 5982 | 0.648129194 | 20 | 0.254971557 | 13 | 0.763582745 | 20
1y08 | 7293 | 0.394266745 | 32 | 0.392633849 | 18 | 0.450255562 | 16
1y09 | 8024 | 0.270133977 | 18 | 0.339197716 | 31 | 0.676444252 | 18
1y10 | 8696 | 0.218536632 | 23 | 0.348983679 | 15 | 0.391750897 | 23

The following result is for CEBSDB database:
File_name | Rpeak_Num | EDR1-Corr | Time-Delay | EDR2-Corr | Time-Delay | EDR3-Corr | Time-Delay
-- | -- | -- | -- | -- | -- | -- | --
b001 | 296 | 0.655777733 | 435 | 0.797495026 | 486 | 0.72178827 | 431
b002 | 307 | 0.699945661 | 399 | 0.755393306 | 448 | 0.824949655 | 335
b003 | 346 | 0.315896073 | 387 | 0.911452818 | 422 | 0.93373099 | 416
b004 | 324 | 0.861385933 | 391 | 0.511376088 | 472 | 0.853120656 | 397
b005 | 361 | 0.948454005 | 409 | 0.877974259 | 432 | 0.945667341 | 410
b006 | 308 | 0.809286095 | 406 | 0.436260162 | 467 | 0.739605814 | 431
b007 | 271 | 0.365172235 | 470 | 0.486472888 | 301 | 0.66283287 | 438
b008 | 477 | 0.912476485 | 390 | 0.239281671 | 433 | 0.918858855 | 394
b009 | 312 | 0.541124745 | 416 | 0.498229271 | 70 | 0.361894892 | 419
b010 | 307 | 0.865887696 | 460 | 0.854241671 | 475 | 0.600751767 | 347
b011 | 336 | 0.877067832 | 421 | 0.810477526 | 466 | 0.871033862 | 434
b012 | 402 | 0.941681388 | 401 | 0.557001476 | 437 | 0.843572902 | 394
b013 | 357 | 0.928253248 | 403 | 0.449616373 | 248 | 0.921370186 | 404
b014 | 343 | 0.824191695 | 447 | 0.607842167 | 464 | 0.765426588 | 434
b015 | 328 | 0.836271284 | 385 | 0.481519556 | 450 | 0.825941313 | 385
b016 | 350 | 0.872791628 | 394 | 0.738602526 | 450 | 0.825028111 | 406
b017 | 364 | 0.957343179 | 418 | 0.749473769 | 431 | 0.950914822 | 413
b018 | 397 | 0.645256384 | 447 | 0.621277018 | 482 | 0.553156845 | 433
b019 | 314 | 0.823206656 | 411 | 0.707293113 | 441 | 0.831463969 | 414
b020 | 335 | 0.578955029 | 479 | 0.646773613 | 511 | 0.792133807 | 472

**Comment by DominiqueMakowski** [comment]
First, note that RSA is undergoing some improvements (@peterhcharlton), which might partly explain why the correlation is lower. Moreover, it seems based on your results that EDR1 is on average better than the one based on the old RSA? So I'd go with that

**Comment by mobilemodem** [comment]
> 

I am trying some ideas to understand better the differences between diffrent EDR signals. But no progress yet.
Hope this issue kept open for future discussion.
