### ISSUE TITLE
Complete method description for new PPG peak detection method

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#788]
@peterhcharlton actually I realized that I forgot to add the new peak detection methods to our report-generating function. Would you be kind to help me write a small paragraph to explain the new methods here:

https://github.com/neuropsychology/NeuroKit/blob/8c564938c5fc2b4a377fd89bb14ac07a430983b9/neurokit2/ppg/ppg_methods.py#L131-L145

Thanks a lot ☺️

**Comment by peterhcharlton** [comment]
Yes will do - I'll work on this next week
