### ISSUE TITLE
Add Ledalab and SparsEDA EDA phasic decomposition methods

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#807]
It would be good if we implemented the two other [popular methods](https://www.mdpi.com/1424-8220/20/2/479#B60-sensors-20-00479) for EDA decomposition, namely Ledalab (the historical one) and sparsEDA.

Good news is that both methods seem to have functional Python translations (from matlab) already, so we can use that as reference. 

- https://github.com/HIIT/Ledapy
- https://github.com/yskong224/SprasEDA-Python

sparsEDA seems the most straightforward to add as it is a fairly self-contained code, but the only problem is that it doesn't have defaults for the [parameters](https://github.com/yskong224/SprasEDA-Python/blob/814e53bf78d1e7534addbbf2ee955e32a1d47b0b/sparsEDA.py#L263), so we cannot test it out of the box. It requires checking in some papers what are good default values:

- Lutin et al. 2021: The application parameters were defined as follows: ε = 0.0001, K_max = 40 iterations, Nmin = 5/4 fs = 10 samples, ρ = 0.025.

**Comment by stasinos** [comment]
In the original MATLAB implementation, epsilon defaults to 1.
