### ISSUE TITLE
ecg_delineate mixes T and P peaks

### ISSUE THREAD

**Issue by HotDog702** [neuropsychology/NeuroKit#809]
If P-peak is not distinct enough, the algorithm erroneously assign it position to previous T-peak (on figure below I omit "onset" and "offset" labels and R-peak mark, but hope, the problem is quite clear)
![image](https://user-images.githubusercontent.com/95288970/227984571-f4263b8e-86bd-45dc-b337-488725ffc553.png)

**Comment by HotDog702** [comment]
Another example of P and R overlapping:
![image](https://user-images.githubusercontent.com/95288970/228815178-2d2af912-4316-4a3b-9fd2-72f3f0d5970d.png)
In ECG there are may be several P, R or T peaks, but their bounds must not overlap

**Comment by danibene** [comment]
Would it be possible for you to provide the code and data to generate a minimal example?

**Comment by DominiqueMakowski** [comment]
@HotDog702 that's not gonna be easy to solve, as it's not just a fix in the current algorithm but would require implementing a new and better one. 

If you're interested, I would invite you to do a quick literature search of the state of the art or ECG delineation algorithm, and see what implementations are available open-source. We can then discuss and potentially integrate some into neurokit.

**Comment by HotDog702** [comment]
Don't quite understand: what is the correct (or at least, expected) order of delineated points?
Pon - P - Poff - Ron - Q - R - S - Roff - Ton -T -Toff , yes ? Could you plot the expected positions on some "ideal" ECG?
Are Ron & Roff correct names? May be Qon & Soff ?
