### ISSUE TITLE
How to classify heartbeats

### ISSUE THREAD

**Issue by paokuaikuai** [neuropsychology/NeuroKit#813]
Normal (N)”, “Ventricular premature beat (V)”, “Supraventricular premature beat (S)

**Comment by DominiqueMakowski** [comment]
Hi, please provide an algorithmic example or references to papers on how to achieve that thanks.

**Comment by DominiqueMakowski** [comment]
That is likely beyond the scope of neurokit. Feel free to reopen this issue if you have a Python classification algorithm that runs and that you would like to add to the package.
