### ISSUE TITLE
Returning total power as heart rate variability feature

### ISSUE THREAD

**Issue by danibene** [neuropsychology/NeuroKit#821]
**Describe the solution you'd like**
What are your thoughts on having total power as an HRV feature? It is currently just used for normalization in NeuroKit but some studies have used it as a feature itself (e.g. several studies mentioned here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5624990/)

**How could we do it?**
It is already computed here: https://github.com/neuropsychology/NeuroKit/blob/d973ae2d9a366c9275f29df3f7ef7c6c70b2ffad/neurokit2/hrv/hrv_frequency.py#L214

So it could be added to the output and maybe called `HRV_TP`?

**Comment by DominiqueMakowski** [comment]
Sounds good :)
