### ISSUE TITLE
Support for real-time data from PolarH10

### ISSUE THREAD

**Issue by gd1925** [neuropsychology/NeuroKit#826]
Hi all,

I wanted to ask, has anyone managed to read the real time data from Bluetooth enabled devices such as PolarH10? I am trying to get ECG waveforms from this device and I am looking for codes that can help me get the data and save it in the form of csv files. Any leads would be super useful. Thank you in advance.

**Comment by JanCBrammer** [comment]
@gd1925, have a look at https://github.com/JanCBrammer/OpenHRV/, and in particular https://github.com/JanCBrammer/OpenHRV/issues/20.

**Comment by gd1925** [comment]
@JanCBrammer , That's awesome! Thank you! That will definitely help!
