### ISSUE TITLE
Questions on EDA processing with Neurokit2

### ISSUE THREAD

**Issue by yingyque** [neuropsychology/NeuroKit#851]
Dear developers,

Hello, this is Ying. I and our team member are using neurokit2 to find SCR features (i.e., EDA peaks). We are having some questions when processing the data. Grateful if you can take a look when you are available. Thanks a lot!

Our EDA signals were collected by the Empatica E4 wristband and the sampling rate is low (4Hz). We found a custom processing pipeline for the data from Empatica provided by isayasMatter in this answer: https://github.com/neuropsychology/NeuroKit/issues/554
![eda_custom_process](https://github.com/neuropsychology/NeuroKit/assets/132443935/b466714f-aaa0-4412-9520-2a9fd1126292)

1. We found you formally provided a function named eda_process() which could return the values of EDA_phasic, SCR_Peaks (https://neuropsychology.github.io/NeuroKit/functions/eda.html#main). Our question is that if it is similar to the output from the aforementioned eda_custom_process which used nk.eda_phasic, nk.eda_peaks. 

2. We observed that in this formal page: https://neuropsychology.github.io/NeuroKit/functions/eda.html#main, the sampling rate in the function of eda_process() indicates "sampling_rate (int) – The sampling frequency of "rsp_signal" (in Hz, i.e., samples/second)". We are not sure if it is a typo that the sampling frequency is equal to rsp_signal instead of the EDA signals.
<img width="777" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/1e7ea473-2ae4-4cd0-9432-8554105a44c9">

3. We are wondering if there are any referenced ranges for the scr_peaks, scr_amplitude, etc. for a certain period of time.

4. We observed "nan" outputs in SCR_Amplitude, SCR_RiseTime, and SCR_RecoveryTime. May I ask what these nan values mean? As we hope to further calculate SCR_Mean_Amplitude, SCR_Max_Amplitude, SCR_Mean_RiseTime, SCR_Mean_RecoveryTime from the above outputs, we propose to remove these "nan" values before further calculation. Does this make sense?

Looking forward to your reply and thank you very much!

Best,
Ying

**Comment by danibene** [comment]
I will try to answer some of your questions:
 
> 1. We found you formally provided a function named eda_process() which could return the values of EDA_phasic, SCR_Peaks (https://neuropsychology.github.io/NeuroKit/functions/eda.html#main). Our question is that if it is similar to the output from the aforementioned eda_custom_process which used nk.eda_phasic, nk.eda_peaks.

`eda_process()` also includes a function to clean the data, whereas the `eda_custom_process()` function you showed does not. This custom pipeline was originally written because the sampling rate of the empatica is too low for the filtering applied in the default cleaning function. 

However, `eda_process()` has been since updated to skip the filtering if the sampling rate is too low, so you should get the same output as `eda_custom_process()`, with a warning:
https://github.com/neuropsychology/NeuroKit/blob/35ed696300626eadd9ae953875556c64ccca9190/neurokit2/eda/eda_clean.py#L104-L108

> 2. We observed that in this formal page: https://neuropsychology.github.io/NeuroKit/functions/eda.html#main, the sampling rate in the function of eda_process() indicates "sampling_rate (int) – The sampling frequency of "rsp_signal" (in Hz, i.e., samples/second)". We are not sure if it is a typo that the sampling frequency is equal to rsp_signal instead of the EDA signals.

Thank you for pointing that out! It's a typo, yes.

> 4. We observed "nan" outputs in SCR_Amplitude, SCR_RiseTime, and SCR_RecoveryTime. May I ask what these nan values mean?

Are these nan values only at the beginning, before the first onset? If so, I think that is to be expected. Feel free to also provide a minimal example with sample data if you'd like to show exactly what your output looks like.

**Comment by DominiqueMakowski** [comment]
And 
3. Not to my knowledge :)
1. If you install the dev version of neurokit, you can use  `eda_process()` directly on your Empatica data (no need to build a custom pipeline)

**Comment by yingquehku** [comment]
Dear [DominiqueMakowski](https://github.com/DominiqueMakowski), 

Thanks for your quick response and answers.

Dear [danibene](https://github.com/danibene),
> Are these nan values only at the beginning, before the first onset? If so, I think that is to be expected. Feel free to also provide a minimal example with sample data if you'd like to show exactly what your output looks like.

Yes, we found there were few nan values at the very beginning of SCR_Onsets and SCR_Amplitude in some sample data (not all sample data). However, it was the most case that there were much more nan values in SCR_Recovery and SCR_RecoveryTime. May I know if is there any explanation for this? Thanks!

The below screenshots were SCR outputs from one sample data, including a couple of nan values at the beginning of SCR_Onsets, SCR_Amplitude, SCR_RiseTime, but more nan values in SCR_Recovery, and SCR_RecoveryTime.
<img width="841" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/7dc2a943-87d3-4cb5-96f7-d8f5e172c2d3">
<img width="829" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/488777d7-87cc-4959-8a7d-3ce50280ee51">
<img width="845" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/80b03e64-74db-4639-829d-fa3aac3abbfd">

The below screenshots were SCR outputs from another sample data, including nan values in SCR_Recovery and SCR_RecoveryTime.
<img width="692" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/40aa6845-e351-459d-aeb9-7d607af6396b">
<img width="847" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/dead3ace-3f67-44db-8a4b-80a7c4d2da37">
<img width="827" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/3f33522d-d75f-49d1-bb9c-ce7b6ca95e66">
<img width="852" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/a2a17c08-9a80-44b8-85ef-7e3fbae6bdc1">

**Comment by danibene** [comment]
@yingquehku would it be possible for you to upload the data directly as well as the code tou used?

**Comment by yingquehku** [comment]
> @yingquehku would it be possible for you to upload the data directly as well as the code tou used?
Sure. I updated the sample data as well as the code in the below attachment. 
Thank you very much!
[scr nan_20230627.zip](https://github.com/neuropsychology/NeuroKit/files/11883216/scr.nan_20230627.zip)

**Comment by danibene** [comment]
@yingquehku thank you! I'll try to have a look at it sometime during the next week or two (unless figures it out before me), feel free to @ me if I don't get back to you by then

**Comment by yingquehku** [comment]
> @yingquehku thank you! I'll try to have a look at it sometime during the next week or two (unless someone else figures it out before me), feel free to @ me if I don't get back to you by then

alright, thanks!

**Comment by DominiqueMakowski** [comment]
Can you add a plot of your signal? In particular in areas when recovery time is missing?

**Comment by yingquehku** [comment]
Thanks Dom for the advice! I followed this instruction (https://neuropsychology.github.io/NeuroKit/examples/eda_peaks/eda_peaks.html) to visualize the SCR features including SCR_Onsets, SCR_Peaks, SCR_Recovery in cleaned EDA signals for 8 passage reading periods of a participant. 

We plotted SCR_Onsets='red', SCR_Peaks='blue', SCR_Recovery='orange'.
From my observation, there were dense lines in the plot with missing recovery time, as the below first figure shows. In contrast, there were sparse lines in the plot without missing recovery time, as the below second figure shows.
<img width="414" alt="1" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/026a61a4-e5d1-4a86-9fe5-aa3d6c7a056c">
<img width="398" alt="2" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/0ce1cb1b-b479-46f4-992f-3347d840f962">

I saved the SCR features outputs as well as the plots in this document: [plot scr features_20230628.docx](https://github.com/neuropsychology/NeuroKit/files/11901143/plot.scr.features_20230628.docx). 
Attached is the code and sample data I used for further reference.
[scr nan_20230628.zip](https://github.com/neuropsychology/NeuroKit/files/11901160/scr.nan_20230628.zip)

**Comment by DominiqueMakowski** [comment]
It seems like you need first to apply some filtering + signal decomposition to your signal before estimating peaks (which should be done on the phasic component). Here the high-frequency noise messes up with the detection

**Comment by yingyque** [comment]
Thanks Dom! I first used cvxEDA in nk.eda_phasic to pre-process the EDA data shown in the above dense-signal figure. The results showed that the data after cvxEDA processing look more reasonable, which decreases the high-frequency noises. 

cvxEDA
<img width="334" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/625cff0b-ccb1-4bd7-9070-4cdbb22f8684">

For the filtering, I tested the "smoothmedian" and the "highpass" embedded in the nk.eda_phasic function, but they seem to less work to remove the high-frequency noises in this case. My question is, as the cvxEDA seems good to solve this situation, do we need to **additionally use another method** to filter the high-frequency noises apart from using cvxEDA? 

smoothmedian
<img width="331" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/da384eaa-f3a4-4994-b14d-404d72c7300e">

highpass
<img width="332" alt="image" src="https://github.com/neuropsychology/NeuroKit/assets/132443935/03a0f09b-230f-4728-aac8-2cb56526a6a5">

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/neuropsychology/NeuroKit/assets/8875533/300bf8ea-b2c5-4513-ba65-3233462aa124)

This image looks like it's the raw data, it has 1) clear phasic peaks (SCRs) and 2) an overall negative drift (which is common), part of the tonic activity. 

Applying eda_phasic extracts the phasic (and the tonic) components: what you should focus on then is the phasic one, which should be on average **flat** (i.e., without the negative trend) and only show the peaks. From your pictures below it seems like you are working with the tonic signal, which should only have a negative trend without peaks (as in the pics)
