### ISSUE TITLE
can neurokit2 code be run on GPU?

### ISSUE THREAD

**Issue by AdarshPandey06** [neuropsychology/NeuroKit#865]
i am trying to run nk.hrv(). it is taking too much time. Can I offload it to GPU? i tried multiple things, It is still running on CPU only.

**Comment by DominiqueMakowski** [comment]
You can try running only lightweight functions, like `hrv_timedomain()` if you want faster estimations. 

There is no straightforward way to make it faster, but if you manage to find ways of making these functions more efficient do let us know
