### ISSUE TITLE
Docs: Tutorials/Example Ideas (and how to contribute)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#87]
# Examples ideas

*Examples are short, specific and self-contained articles about specific topics or possibilities.*

- [x] **Understanding NeuroKit**: how to see what a function does in the docs, then its code on github, then where is the code located on your machine, and where you can try to make changes/fixes
- [x] **How to contribute**: once some change/fixes are mde, how to push back to github. With screenshots etc. (all steps from when github desktop is installed to PR)
- [x] **How to help with the documentation**: Pretty much what I wrote below, + also different types of documentation (i.e., examples, docstrings, etc) 
- [x] **Building a custom processing pipeline**: Where to see how a pipeline is made, and how to build a new function with a custom routine
- [x] **Get familiar with Python in 10min**: Crash course to python presenting the basics useful for using neurokit 
- [ ] **How to record ECG**: Documenting how to position electrodes etc.
- [ ] **Heart rate and artefacts detection**: About the peaks artefacts detection, visualization etc. (@JohnDoenut do you have some ideas?)
- [x] **Event-related analysis**: there is a basis in NK1's doc
- [x] **Interval-related analysis**: how to do get physiological features for longer periods (example with resting state)
- [x] **How to create epochs**: How to create epochs of data, either from one signal (showing events detection, and documenting the `epochs_create` function) or from multiple data (when people have different files for each subject), how to read them in a loop and put them in a `dict` and format it as epochs so it can be further analyzed.
- [x] **Extract and visualize heartbeats (QRS)**: Check if R peaks correctly detected, and adjust the method if need be. Then, extract and plot all R peaks and QRS complexes.
- [ ] **Find average respiration rate**: Get average heart rate and RSP rate (e.g., https://python-heart-rate-analysis-toolkit.readthedocs.io/en/latest/heartrateanalysis.html)
- [ ] **Heart Rate Variability (HRV)**: once we have HRV, write about cardiac coherence (what it is, what it isn't, how to estimate it) ([inspiration](https://www.kubios.com/about-hrv/))
- [x] **Electrodermal Activity (EDA) analysis**: phasic, tonic, SCR's features etc. (https://imotions.com/blog/skin-conductance-response/; https://support.mindwaretech.com/2018/04/all-about-eda-part-2-components-of-skin-conductance/)
- [ ] **Working with non-human data**: Showing another applied example of "building a custom pipeline" (#104)
- [ ] **Derive respiration from ECG**: ECG-Derived Respiration (EDR).
- [x] **Respiration Rate Variability (RRV)**: Small example showing how to compute RRV indices. (@zen-juen). With a "hint box" saying "what if I don't have respiration data?" and linking to the above example on EDR.
- [x] **Simulate Physiological Signals using Python**: Showcasing simulation function and their parameters.
- [ ] ...

# How to contribute

## How to write
The documentation that is on the [website](https://neurokit2.readthedocs.io/en/latest/) is automatically built by the hosting website, readthedocs, from [reStructured Text (RST) files](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html) (a syntax similar to markdown) or from [jupyter notebooks (.ipynb)](https://jupyter.org/). Notebooks are preferred if your example contains code and images.

## Where to add the files

These documentation files that we need to write are located in the [/docs/](https://github.com/neuropsychology/NeuroKit/tree/master/docs) folder. For instance, if you want to add an example, you need to create a new file, for instance `myexample.rst`, in the `docs/examples/` folder.

If you want to add images to an `.rst` file, best is to put them in the [`/docs/img/`](https://github.com/neuropsychology/NeuroKit/tree/master/docs/img) folder and to reference their link.

However, in order for this file to be easily **accessible from the website**, you also need to add it to the **table of content** located in the [index](https://github.com/neuropsychology/NeuroKit/blob/master/docs/examples/index.rst) file (just add the name of the file without the extension).

# Examples of good documentation

- [Analysing a Noisy ECG Signal](https://github.com/paulvangentcom/heartrate_analysis_python/blob/master/examples/5_noisy_ECG/Analysing_Noisy_ECG.ipynb)
- [Analyzing a Discrete Heart Rate Signal Using Python](http://www.paulvangent.com/2016/03/15/analyzing-a-discrete-heart-rate-signal-using-python-part-1/)

**Comment by JohnDoenut** [comment]
>     * **Heart rate and artefacts detection**: About the peaks artefacts detection, visualization etc. (@JohnDoenut do you have some ideas?)

@DominiqueMakowski , happy to add an example about a simple workflow from raw ECG to heartrate. This would include some background on artifact detection and correction and why it's important (although dealing with artifacts is even more of a necessity for HRV computation I guess).
