### ISSUE TITLE
[Feature] Including random_state in complexity_symbolize

### ISSUE THREAD

**Issue by danibene** [neuropsychology/NeuroKit#879]
**Describe the solution you'd like**
I noticed here https://github.com/neuropsychology/NeuroKit/actions/runs/5825029169/job/15800820430?pr=863 that the docstring of `complexity_symbolize()` raises a warning:
```
 >>>-------------------------------------------------------------------------
Warning in D:\a\NeuroKit\NeuroKit\neurokit2\complexity\utils_complexity_symbolize.py:docstring of neurokit2.complexity.utils_complexity_symbolize.complexity_symbolize at block ending on line 131
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\scipy\cluster\vq.py:602: UserWarning: One of the clusters is empty. Re-run kmeans with a different initialization.
  warnings.warn("One of the clusters is empty. "
<<<-------------------------------------------------------------------------
```

I was wondering if it would make sense to add an argument to make the initialization deterministic if specified by the user.

**How could we do it?**
We could add `random_state` as an optional argument to `complexity_symbolize()` and then pass that as the `seed` argument of https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans2.html#scipy.cluster.vq.kmeans2
Then we could fix `random_state` in the docstring so that the results are consistent.

**Comment by DominiqueMakowski** [comment]
good catch, sounds good!
