### ISSUE TITLE
Question on page /_modules/neurokit2/ecg/ecg_clean.html

### ISSUE THREAD

**Issue by PhD-GOAT** [neuropsychology/NeuroKit#880]
I want to know the meaning of butterworth_zi. What kind of method is this? For example, in the qrs algorithm of pan-tomp, there are differential, integral, and moving average calculations, is that included in the zi method?

**Comment by danibene** [comment]
Hi @PhD-GOAT , butterworth_zi is a method of filtering, see https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.sosfilt_zi.html

The other preprocessing steps of the pan-tompkins algorithm come after this filtering step and are implemented here: 
https://github.com/neuropsychology/NeuroKit/blob/e7493ed8f2b90b03daebaa1905920f6d482bd130/neurokit2/ecg/ecg_findpeaks.py#L289-L307
