### ISSUE TITLE
Issue on page /_modules/neurokit2/eda/eda_intervalrelated.html

### ISSUE THREAD

**Issue by michalgnacek** [neuropsychology/NeuroKit#885]
eda_intervalrelated function does not accept a parameter "sampling_rate" as per documentation.

**Comment by danibene** [comment]
Have you tried updating to the newest version of neurokit2? "sampling_rate" is a parameter in the current version: https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/eda/eda_intervalrelated.py#L12
