### ISSUE TITLE
Cleaning PPG data

### ISSUE THREAD

**Issue by wchiaching6** [neuropsychology/NeuroKit#887]
Hello NeuroKit Team:

I have a question about cleaning PPG data. I used nk.ppg_clean() to clean raw PPG, process with nk.ppg_process() and got the diagram with nk.ppg_plot(). In the diagram, I saw some abnormal heart rates (<50 or >150 bpm). I wonder if there are methods I can do to further refine the data. Thank you so much.

**Comment by danibene** [comment]
Have you tried using [`signal_fixpeaks()`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/signal/signal_fixpeaks.py)? You could create a [custom processing function](https://neuropsychology.github.io/NeuroKit/examples/bio_custom/bio_custom.html) including it

**Comment by wchiaching6** [comment]
Thank you for pointing out the resources! I will try that out!

**Comment by DominiqueMakowski** [comment]
It's on the roadmap on improve the PPG processing pipeline and incorporate fixpeaks into the default pipeline

**Comment by wchiaching6** [comment]
I tried the signal_fixpeaks, and the results improved a lot. Thank you!
