### ISSUE TITLE
Simple Question on Upsampling after Processing

### ISSUE THREAD

**Issue by melisasaygin** [neuropsychology/NeuroKit#909]
**Question and context**
I have respiration data coming from three different devices. One has a sampling frequency of 250 Hz, other has 256 Hz, and other has 1000 Hz. After I use the process function with their original sampling rates, I need to sync them via cross-correlation, and in this process I upsampled each to 1000 Hz post-processing. Now they are all synced and have a frequency of 1000 Hz. I can just go ahead and use the feature extraction functions by inputting 1000. right? And what if I am "manually" calculating the features by using the processed dataframe itself, is this upsampled version still alright to calculate these?

**Comment by DominiqueMakowski** [comment]
yes that should be alright, especially for respiration data which doesn't require millisecond accuracy

**Comment by melisasaygin** [comment]
Thank you!
