### ISSUE TITLE
ecg_plot(): add all heart beats

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#91]
We could add also, either below or on the side (related the example on how to "manually" get this plot #87), a plot with all the heartbeats plotted on top of each other (with markers on the different waves). Related to delineation #89

**Comment by DominiqueMakowski** [comment]
@Tam-Pham can you attach a screenshot here of the current output

**Comment by zen-juen** [comment]
![Figure_1](https://user-images.githubusercontent.com/54053748/73737620-eb286a80-477d-11ea-94ca-3aa39abf11f8.png)

**Comment by DominiqueMakowski** [comment]
- [ ] Add PQST peaks
- [ ] Thinerl lines for individual heartbeats?
