### ISSUE TITLE
Issue on page /_modules/neurokit2/ppg/ppg_peaks.html

### ISSUE THREAD

**Issue by ejpretty** [neuropsychology/NeuroKit#913]
Hi all! I'm trying to process some PPG data at the moment, I'm going step by step rather than using the ppg_process function, but I keep getting this error:

AttributeError: module 'neurokit2' has no attribute 'ppg_peaks'. Did you mean: 'ecg_peaks'?

My version of neurokit is the latest one: neurokit2-0.2.6

Thanks in advance!

Edit: I saw there was a post earlier with a similar problem, and they fixed it by installing 0.2.5 and then reinstalling 0.2.6. I did this, restarted pycharm and it was fixed

**Comment by DominiqueMakowski** [comment]
Great that you got it fixed ☺️
