### ISSUE TITLE
Resources: EMG processing and features

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#93]
## Features

- [x] Amplitude
- [x] Onsets/offsets of activation
- [ ] ...

## Resources

- [Reaz et al., 2006](https://link.springer.com/content/pdf/10.1251/bpo115.pdf)
- [Farfan et al., 2010](https://link.springer.com/article/10.1186/1475-925X-9-72)
- [Merletti et al., 2010](http://www.dl.begellhouse.com/en/journals/4b27cbfc562e21b8,606681d65e2ccb94,45714f720ecf76f5.html)
- [Zhang et al., 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3514830/)
- [Wang et al., 2013](https://pdfs.semanticscholar.org/c348/f06416aa03154c40bb82d5b26cef40e5840d.pdf)

**Comment by zen-juen** [comment]
`emg_plot` now marks onsets, offsets, and regions of activity greater than the specified threshold!
![emg](https://user-images.githubusercontent.com/54053748/74082129-d7d51200-4a91-11ea-9454-a6de874d76b5.png)

**Comment by DominiqueMakowski** [comment]
Aesthetic suggestions: Maybe instead of points for onsets/offsets, adding back grey vertical dashed lines behind would better represent the activation phases 😅

**Comment by zen-juen** [comment]
Hmmmmm
![Figure_1](https://user-images.githubusercontent.com/54053748/74082680-508a9d00-4a97-11ea-8ebc-13c1cb4776e5.png)

**Comment by DominiqueMakowski** [comment]
😬 we can mark onsets and offsets the same colour in the plot ('cause it's pretty obvious which one is which). And maybe plotting the vertical lines behind? As for the legend, I'd only put the orange line saying "Amplitude", the rest is rather explicit (?)

**Comment by zen-juen** [comment]
🗡🗡🗡🗡🗡🗡🗡

**Comment by zen-juen** [comment]
![Figure_1](https://user-images.githubusercontent.com/54053748/74096844-ee857280-4b3e-11ea-955d-837cc87a3228.png)
