### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Lukas-J** [neuropsychology/NeuroKit#945]
When running a programme using neurokit on a brand-new container, python complains that the requests module is missing. 

I resolved this by running `pip install requests`

requests is imported by https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/data/database.py

A desired solution would be to add "requests" to the list of requirements (maybe in https://github.com/neuropsychology/NeuroKit/blob/master/setup.py#L30 ?), so its get installed by `pip install neurokit2` automatically.

Cheers!

**Comment by DominiqueMakowski** [comment]
It is fixed on the dev branch, which you can install with:

`pip install https://github.com/neuropsychology/neurokit/zipball/dev --upgrade`
