### ISSUE TITLE
EDA analyze function does not use correct sampling rate 

### ISSUE THREAD

**Issue by tilly111** [neuropsychology/NeuroKit#972]
Hello, 
while working with the EDA analyze method I found that it does not use the correct sampling rate if you do not use the default one (sampling_rate=1000). The problem is, that the sampling rate is not forwarded to the internal methods, see for example: https://github.com/neuropsychology/NeuroKit/blob/3d004b4777c3e59b288f46b9f0f812ac1e04b5d4/neurokit2/eda/eda_analyze.py#L100
A fix would be to just add this parameter to the internal methods, like
`
features = eda_intervalrelated(data, sampling_rate=sampling_rate)
`.

**Comment by danibene** [comment]
Thank you for catching this! Feel free to open a PR with the suggested changes :)
