### ISSUE TITLE
Senior project

### ISSUE THREAD

**Issue by Brandoncheaa** [neuropsychology/NeuroKit#983]
**Question and context**
Hello to anyone that may be able to guide me,

I am working on my senior project involving sleep staging, my task involves implement an algorithm to classify sleep stages. My partner is currently working on the hardware to acquire and store real world data. I on the other hand am task with formatting and implementing a seamless transition from him gathering the real world data to just simply plugging it into the algorithm, if anyone is interested we are utilizing SleepyCo(https://github.com/gist-ailab/SleePyCo). I am here because I found somewhere online that I could utilize NeuroKit2 to generate synthetic EEG data related to sleep staging, we are planning to run our machine for 9 hours, generating 16 bit data at a sampling rate of 500Hz. If anyone could steer me in the right direction as to how I would be able to generate this synthetic data I would greatly appreciate it, I am having a hard time navigating all the folders.

Thank you,
Brandon Chea

**Comment by DominiqueMakowski** [comment]
Hi @Brandoncheaa, sorry no NeuroKit does not provide EEG signal simulation for now, good luck!
